/* ── UI translation packages ──
   The English catalog (EN) is the source of truth and the fallback for any
   missing key. Each language package in LANGUAGE_PACKAGES only needs to
   override the keys it has translated — everything else falls back to EN.
   Every language code that can be selected in the interface is supported:
   getLanguagePackage(code) always returns a usable package.
*/

export const LANGUAGE_CODES = [
  'af', 'am', 'ar', 'arc', 'as', 'ay', 'az', 'ba', 'bal', 'bam', 'bar', 'be', 'bem', 'ber', 'bg',
  'bi', 'bjz', 'bn', 'bo', 'bodo', 'bs', 'bwg', 'ca', 'cal', 'ceb', 'ch', 'ckb', 'cnr', 'crs', 'cs',
  'cv', 'cy', 'da', 'de', 'doi', 'dv', 'dz', 'ee', 'el', 'en', 'es', 'et', 'eu', 'ewo', 'fa', 'fi',
  'fil', 'fj', 'fo', 'fr', 'fy', 'ga', 'gd', 'gil', 'gl', 'gn', 'gsw', 'gu', 'gv', 'ha', 'he',
  'hgm', 'hi', 'hif', 'ho', 'hr', 'ht', 'hu', 'hy', 'hz', 'id', 'ig', 'ilo', 'is', 'it', 'ja',
  'jam', 'jv', 'ka', 'kck', 'kg', 'khi', 'ki', 'kk', 'kl', 'km', 'kn', 'ko', 'kok', 'kri', 'ks',
  'ku', 'kwn', 'ky', 'la', 'lb', 'lg', 'ln', 'lo', 'loz', 'lt', 'lua', 'luo', 'lv', 'mai', 'mey',
  'mfe', 'mg', 'mh', 'mi', 'mk', 'ml', 'mn', 'mni', 'mr', 'ms', 'mt', 'my', 'na', 'nah', 'nan',
  'nb', 'nd', 'ndc', 'ne', 'nfr', 'ng', 'niu', 'nl', 'nn', 'no', 'nr', 'nrf', 'nso', 'ny', 'nzs',
  'om', 'or', 'pa', 'pap', 'pau', 'pih', 'pl', 'pov', 'prs', 'ps', 'pt', 'qu', 'rar', 'rm', 'rn',
  'ro', 'ru', 'rw', 'sat', 'sd', 'se', 'sg', 'si', 'sk', 'sl', 'sm', 'smi', 'sn', 'so', 'sq',
  'sr', 'srn', 'ss', 'st', 'su', 'sv', 'sw', 'ta', 'te', 'tet', 'tg', 'th', 'ti', 'tk', 'tkl',
  'tl', 'tn', 'to', 'toi', 'tpi', 'tr', 'ts', 'tt', 'tvl', 'tw', 'ug', 'uk', 'ur', 'uz', 've',
  'vi', 'wo', 'wuu', 'xh', 'yo', 'yua', 'yue', 'zdj', 'zh', 'zib', 'zu',
]

/* ── English base catalog ── */
export const EN = {
  // common
  'common.loading': 'Loading...',
  'common.loadingShort': 'Loading',
  'common.back': 'Back',
  'common.close': 'Close',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.next': 'Next',
  'common.or': 'or',
  'common.continue': 'Continue',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.notYet': 'Not Yet',
  'common.search': 'Search',
  'common.retry': 'Retry',
  'common.change': 'Change',
  'common.send': 'Send',
  'common.edit': 'Edit',
  'common.delete': 'Delete',
  'common.view': 'View',
  'common.unknown': 'Unknown',
  'common.you': 'You',
  'common.anonymous': 'Anonymous',
  'common.reader': 'Reader',
  'common.default': 'Default',
  'common.poem': 'poem',
  'common.poems': 'poems',
  'common.book': 'book',
  'common.books': 'books',
  'common.day': 'day',
  'common.days': 'days',
  'common.share': 'Share',
  'common.byAuthor': 'by {author}',
  'common.update': 'Update',
  'common.cachedOffline': 'Cached data — offline',
  'common.syncedServer': 'Synced with server',

  // nav
  'nav.home': 'Home',
  'nav.read': 'Read',
  'nav.writings': 'My Writings',
  'nav.writeNow': 'Write Now',
  'nav.writeNew': 'Write New',
  'nav.writeAPoem': 'Write a poem',
  'nav.favorites': 'Favourites',
  'nav.favoriteLines': 'Favorite Lines',
  'nav.blend': 'Blend',
  'nav.inbox': 'Inbox',
  'nav.shelf': 'My Shelf',
  'nav.notifications': 'Notifications',
  'nav.settings': 'Settings',
  'nav.terms': 'Terms',
  'nav.privacy': 'Privacy Policy',
  'nav.about': 'About',
  'nav.changelog': 'Changelog',
  'nav.categories': 'Categories',
  'nav.findYourBook': 'find your book',
  'nav.addYourBooks': 'add your books',
  'nav.latestMessages': 'latest messages',
  'nav.menu': 'Menu',
  'nav.profile': 'Profile',

  // auth
  'auth.poetry': 'Poetry',
  'auth.welcomeBack': 'Welcome back, poet',
  'auth.join': 'Join Poetry',
  'auth.username': 'Username',
  'auth.enterUsername': 'Enter username',
  'auth.password': 'Password',
  'auth.enterPassword': 'Enter password',
  'auth.signingIn': 'Signing in...',
  'auth.signIn': 'Sign In',
  'auth.continueWithGoogle': 'Continue with Google',
  'auth.createAccount': 'Create an account',
  'auth.forgotPassword': 'Forgot password?',
  'auth.fillAllFields': 'Fill all fields',
  'auth.chooseUsername': 'Choose a unique username',
  'auth.setupProfile': 'Set up your profile',
  'auth.setSecurityQuestion': 'Set a security question',
  'auth.usernamePlaceholder': 'Choose a username (min 3 chars)',
  'auth.checking': 'checking...',
  'auth.available': '✓ available',
  'auth.taken': '✗ taken',
  'auth.suggestions': 'Suggestions:',
  'auth.alreadyHaveAccount': 'Already have an account?',
  'auth.displayName': 'Display Name',
  'auth.howOthersSeeYou': 'How others see you',
  'auth.min6Chars': 'Min 6 characters',
  'auth.retypePassword': 'Retype Password',
  'auth.reenterPassword': 'Re-enter password',
  'auth.securityQuestion': 'Security Question',
  'auth.securityQuestionExample': "e.g. What was your first pet's name?",
  'auth.yourAnswer': 'Your Answer',
  'auth.enterYourAnswer': 'Enter your answer',
  'auth.creating': 'Creating...',
  'auth.createAccountBtn': 'Create Account',
  'auth.enterYourDisplayName': 'Enter your display name',
  'auth.passwordMin6': 'Password must be at least 6 characters',
  'auth.passwordsDontMatch': 'Passwords do not match',
  'auth.fillBothFields': 'Fill both fields',
  'auth.enterUsernameToFind': 'Enter your username to find your account',
  'auth.answerYourSecurityQuestion': 'Answer your security question',
  'auth.chooseNewPassword': 'Choose a new password',
  'auth.yourUsername': 'Your username',
  'auth.lookingUp': 'Looking up...',
  'auth.findAccount': 'Find Account',
  'auth.securityQuestionColon': 'Security Question:',
  'auth.yourAnswerShort': 'Your answer',
  'auth.checkingEllipsis': 'Checking...',
  'auth.verifyAnswer': 'Verify Answer',
  'auth.newPasswordMin6': 'New password (min 6 chars)',
  'auth.resetting': 'Resetting...',
  'auth.resetPassword': 'Reset Password',
  'auth.forgotPasswordHeading': 'Forgot Password',
  'auth.backToSignIn': 'Back to Sign In',
  'auth.enterUsernameToFindSecurity': 'Enter your username to find your security question.',
  'auth.resetSuccess': 'Password reset. Sign in with your new password.',
  'auth.resetNeedsBackend': 'Password reset requires Edge Functions to be deployed. Use Supabase Dashboard for now.',
  'auth.accountCreated': 'Account created! Sign in below.',
  'auth.usernameMin3': 'Username must be at least 3 characters',
  'auth.usernameCheckFail': 'Could not check username — please try again.',
  'auth.usernameTaken': 'Username taken — try one below',
  'auth.fillSecurityQA': 'Fill security question and answer',
  'auth.usernameNotFound': 'Username not found',
  'auth.answerTheSecurityQuestion': 'Answer the security question',
  'auth.throttle': 'Please wait a few seconds before trying again.',
  'auth.tooManySignups': 'Too many signups. Please wait 1 minute and try again.',
  'auth.usernameTakenErr': 'Username already taken',
  'auth.invalidCredentials': 'Invalid username or password',
  'auth.noSecurityQuestion': 'No security question found for this user',
  'auth.enterUsernameErr': 'Enter your username',
  'auth.enterAnswerErr': 'Enter your answer',
  'auth.createAccountPrompt': 'Already have an account? Sign in',
  'auth.stepChooseUsername': 'Choose Username',
  'auth.stepSetYourName': 'Set Your Name',
  'auth.stepSetLocation': 'Set Location',
  'auth.stepSetPassword': 'Set Password',
  'auth.stepSecurityQuestion': 'Security Question',
  'auth.progressUsername': 'Username',
  'auth.progressName': 'Name',
  'auth.progressLocation': 'Location',
  'auth.progressPassword': 'Password',
  'auth.progressSecurity': 'Security',
  'auth.whatShouldWeCallYou': 'What should we call you?',
  'auth.locationRequired': 'Your location is required — it auto-detects, or pick your country and enter your ZIP / PIN code.',
  'auth.passwordMin6Chars': 'Password (min 6 chars)',
  'auth.retypePasswordLower': 'Retype password',
  'auth.securityQuestionPlaceholder': 'Security question (for password reset)',
  'auth.securityAnswer': 'Security answer',
  'auth.userFallback': 'User',
  'auth.securityDataNotFound': 'Security data not found',
  'auth.signOut': 'Sign Out',

  // dashboard
  'dashboard.readyToShare': 'Ready to share a book?',
  'dashboard.updateBookshelf': 'Update your bookshelf',
  'dashboard.needBook': 'Need a book?',
  'dashboard.blendPromo': 'Click here and discover who might have a copy of what you are looking for.',
  'dashboard.booksNearYou': 'Books Near You',
  'dashboard.openBlend': 'Open Blend →',
  'dashboard.identitiesPrivate': 'Identities stay private until a reader accepts your request.',
  'dashboard.status': 'Status →',
  'dashboard.favoriteLine': 'Favorite Line',
  'dashboard.swipeCard': 'Swipe card to browse',
  'dashboard.welcomeBack': 'Welcome back,',
  'dashboard.welcomeTo': 'Welcome to {site}',
  'dashboard.welcomeHeading': 'Welcome to Blendly',
  'dashboard.welcomeSubtitle': 'A repository of independent and historic literature',
  'dashboard.welcomeTagline': 'Blendly lets you share books to nearby strangers',
  'dashboard.welcomeFeatureRead': 'Read historic & indie poetry',
  'dashboard.welcomeFeatureShare': 'Share books with nearby readers',
  'dashboard.welcomeFeatureDiscover': 'Discover new voices & verses',
  'dashboard.discoverCreate': 'Discover & Create',
  'dashboard.signInToSave': 'Sign In',
  'dashboard.users': 'Users',
  'dashboard.active': 'Active',
  'dashboard.writings': 'Writings',
  'dashboard.independentWritings': 'Independent writings',
  'dashboard.onlineNow': 'Online now',
  'dashboard.newsletterEntries': 'Newsletter entries',
  'dashboard.historicCount': '{count} historic',
  'dashboard.heroMission': 'From the verses of prehistoric and ancient times to the poems written tonight, we carry humanity\'s literature forward — and connect you with like-minded readers to share real books through Blend.',
  'dashboard.heroSafety': 'Stay safe: never share personal information, and always strictly follow the Privacy Policy.',
  'dashboard.joinNewsletter': 'Join the Newsletter',
  'dashboard.newsletterBlurb': 'Selective daily wisdom through your mail — a single thoughtful verse and note, every day.',
  'dashboard.newsletterSuccess': "You're in! Watch your inbox tomorrow.",
  'dashboard.emailPlaceholder': 'you@example.com',
  'dashboard.joining': 'Joining…',
  'dashboard.join': 'Join',
  'dashboard.newsletterFailed': "Couldn't subscribe right now. Please try again.",
  'dashboard.recentlyViewed': 'Recently Viewed',
  'dashboard.trendingPoems': 'Trending Poems',
  'dashboard.latestPoems': 'Latest Poems',
  'dashboard.by': 'by {author}',
  'dashboard.myWritings': 'My Writings',
  'dashboard.new': '+ New',
  'dashboard.noWritingsTap': 'No writings yet. Tap + to write your first poem.',
  'dashboard.viewAllWritings': 'View all {count} writings →',
  'dashboard.startReading': 'Start Reading',
  'dashboard.swipeToExplore': 'Swipe to explore',

  // poetry
  'poetry.noMorePoems': 'No more poems',
  'poetry.tapToRead': 'Tap to read full poem →',
  'poetry.historic': 'Historic',
  'poetry.readFullPoem': 'Read Full Poem',
  'poetry.collapse': 'Collapse',
  'poetry.noPoemSelected': 'No poem selected',
  'poetry.swipeSideways': 'Swipe sideways to switch',
  'poetry.swipe': 'Swipe',
  'poetry.lines': '{count} lines',
  'poetry.titlePlaceholder': 'Poem title...',
  'poetry.bodyPlaceholder': 'Write your poem here...',
  'poetry.categories': 'Categories (up to 3):',
  'poetry.historicNotRatable': 'Historic poem · not ratable',
  'poetry.tapToSaveFavorite': 'Double-tap a line to save as favorite',
  'poetry.tapToRemoveFavorite': 'double-tap again to remove',
  'poetry.swipeOr': 'Swipe or',
  'poetry.prev': 'Prev',
  'poetry.next': 'Next',
  'poetry.editPoem': 'Edit Poem',
  'poetry.writeAPoem': 'Write a Poem',
  'poetry.update': 'Update',
  'poetry.save': 'Save',
  'poetry.titleYourPoem': 'Title your poem...',
  'poetry.untitled': 'Untitled',

  // categories
  'category.love': 'Love',
  'category.nature': 'Nature',
  'category.philosophy': 'Philosophy',
  'category.tragedy': 'Tragedy',
  'category.hope': 'Hope',
  'category.spirituality': 'Spirituality',
  'category.freedom': 'Freedom',
  'category.war': 'War',
  'category.death': 'Death',
  'category.joy': 'Joy',
  'category.reflection': 'Reflection',
  'category.fantasy': 'Fantasy',
  'categories.title': 'Categories',
  'categories.empty': 'No categories available.',
  'categories.noPoems': 'No poems in this category.',

  // blend
  'blend.couldNotLoad': 'Could not load nearby books — please try again.',
  'blend.searchFailed': 'Search failed — try again.',
  'blend.signInToRequest': 'Sign in to request a book',
  'blend.requestMessage': 'Hai, I\'m interested in reading "{title}" can you please share.',
  'blend.requestSent': 'Request sent to a nearby reader for "{title}"',
  'blend.searchPlaceholder': 'Search a book by title or author…',
  'blend.yourBlend': 'Your blend',
  'blend.requestThisBook': 'Request this book',
  'blend.emptyState': 'Use the search bar above to find a book — discover nearby readers who have it.',
  'blend.emptySubtext': 'Your books travel the world, one reader at a time.',
  'blend.findingBooks': 'Finding books near you...',
  'blend.noBooks': 'No books listed yet. Try searching by name, or add a book to your shelf to make it findable.',
  'blend.selfOnly': 'You have this book on your shelf, but no other reader nearby has listed it yet.',
  'blend.resultFound': '{count} book found for "{query}"',
  'blend.resultsFound': '{count} books found for "{query}"',
  'blend.ongoingBlend': '{count} ongoing blend',
  'blend.ongoingBlends': '{count} ongoing blends',
  'blend.noOngoing': 'No ongoing blends yet. Search above or tap a book under "Books Near You" to start a request.',
  'blend.readerHidden': 'Reader details stay hidden — they are shared only after they accept your request in the inbox.',
  'blend.awaitingResponse': 'Awaiting response',
  'blend.accepted': 'Accepted',
  'blend.declined': 'Declined',
  'blend.readerNearby': 'Reader nearby',

  // shelf
  'shelf.empty': 'Add books you would like to circulate for free.',
  'shelf.emptySubtext': 'It may or may not return back, but it sure travels among the world.',
  'shelf.addBook': 'Add a Book',
  'shelf.titlePlaceholder': 'Title *',
  'shelf.subtitlePlaceholder': 'Subtitle (optional)',
  'shelf.pageCountPlaceholder': 'Page count',
  'shelf.authorPlaceholder': 'Author *',
  'shelf.summaryPlaceholder': 'Summary about the book (optional)',
  'shelf.addToShelf': 'Add to Shelf',
  'shelf.trackExchange': 'Exchange Tracking',
  'shelf.markAsSent': 'Mark as Sent',
  'shelf.sentConfirm': 'Have you sent the book yet?',
  'shelf.yesSent': 'Yes, Sent',
  'shelf.notYet': 'Not Yet',
  'shelf.sent': 'Sent ✓',
  'shelf.yesReceived': 'Yes, Received',
  'shelf.receivedComplete': 'Received ✓ - Exchange complete',
  'shelf.removeFromShelf': 'Remove from Shelf',
  'shelf.addAnother': '+ Add Another Book',
  'shelf.pages': '{count} pages',
  'shelf.available': 'Available',
  'shelf.inTransit': 'In transit',

  // inbox
  'inbox.bookRequest': 'Book request',
  'inbox.shared': 'Shared',
  'inbox.sharedWithYou': 'Shared with you',
  'inbox.declined': 'Declined',
  'inbox.received': 'Received',
  'inbox.exchangeComplete': 'Exchange complete',
  'inbox.sharePrompt': '{contact} wants to borrow "{title}". Would you like to share?',
  'inbox.receivePrompt': '{contact} shared "{title}" with you. Did you receive it?',
  'inbox.messagePlaceholder': 'Message...',
  'inbox.empty': 'No conversations yet.',
  'inbox.emptyHint': 'Request a book through Blend to start a conversation.',
  'inbox.replySent': 'Reply sent to {contact}',
  'inbox.re': 'Re: {title}',
  'inbox.agreedShare': 'You agreed to share "{title}" with {contact}',
  'inbox.declinedShare': 'You declined sharing "{title}"',
  'inbox.addedToShelf': '"{title}" added to your shelf',
  'inbox.notYetReceived': 'Not yet received.',
  'inbox.markedNotReceived': 'Marked as not received yet',

  // profile
  'profile.title': 'Profile',
  'profile.writings': 'Writings',
  'profile.favorites': 'Favorites',
  'profile.shelf': 'Shelf',
  'profile.streak': 'Streak',
  'profile.shelfBooks': '({count} books)',
  'profile.addYourBooks': '(add your books)',
  'profile.findYourBook': '(find your book)',
  'profile.myWritingsCount': 'My Writings ({count})',
  'profile.favoriteLinesCount': 'Favorite Lines ({count})',
  'profile.notifications': 'Notifications',
  'profile.couldNotLoad': 'Could not load this profile — try again.',
  'profile.loading': 'Loading profile...',
  'profile.noReader': 'No reader found for "@{username}".',
  'profile.readingStreak': 'reading streak',
  'profile.bestStreak': 'best streak',
  'profile.streakDay': '{count} day',
  'profile.streakDays': '{count} days',
  'profile.favoriteLines': 'Favorite Lines',
  'profile.noFavoritesShared': 'No favorite lines shared yet.',
  'profile.bookshelfCount': 'Bookshelf ({count})',
  'profile.noBooks': 'No books on the shelf yet.',
  'profile.recentlyRead': 'Recently Read',
  'profile.noRecent': 'No recent reads yet.',
  'profile.frequentlyRead': 'Frequently Read',
  'profile.noPatterns': 'No reading patterns yet.',
  'profile.readCount': '{count}x',

  // notifications
  'notifications.clearAll': 'Clear all',
  'notifications.empty': 'No notifications.',
  'notifications.title': 'Notifications',
  'notifications.dailyFavoritesTitle': 'Daily favorite reminder',
  'notifications.dailyFavoritesOne': 'You have 1 saved favorite — come read it today.',
  'notifications.dailyFavoritesMany': 'You have {count} saved favorites — come read them today.',
  'notifications.newRequest': 'New blend request for "{title}" from {from}',
  'notifications.newMessage': 'New message from {from}',

  // favorites
  'favorites.clearAll': 'Clear all',
  'favorites.empty': 'No favorite lines yet.',
  'favorites.hint': 'Triple-tap a line while reading to save it as a favorite.',
  'favorites.attribution': '— {poem} by {author}',
  'favorites.shareQuote': 'Share this quote',
  'favorites.previousPage': 'Previous page',
  'favorites.nextPage': 'Next page',
  'favorites.pageOf': 'Page {page} of {count}',

  // writings
  'writings.empty': 'No writings yet.',
  'writings.cta': 'Write your first poem',
  'writings.writePoem': 'Write a Poem',
  'writings.editPoem': 'Edit Poem',
  'writings.titlePlaceholder': 'Title your poem...',
  'writings.contentPlaceholder': 'Write your poem here...',
  'writings.categoriesHint': 'Categories (up to {count}):',

  // terms / privacy / about
  'terms.title': 'Terms & Conditions',
  'terms.acceptanceHeading': 'Acceptance of Terms',
  'terms.acceptanceBody': 'By using Poetry, you agree to these terms. All poems shared remain the intellectual property of their respective authors.',
  'terms.disclaimerHeading': 'Service Disclaimer',
  'terms.disclaimerBody': 'This service is provided "as is" without warranties. We reserve the right to update these terms at any time.',
  'terms.responsibilitiesHeading': 'User Responsibilities',
  'terms.responsibilitiesBody': 'You are solely responsible for the content you publish. Prohibited activities include posting unlawful, harmful, or plagiarized material.',
  'terms.terminationHeading': 'Termination',
  'terms.terminationBody': 'We may suspend or terminate access for violations of these terms.',
  'privacy.title': 'Privacy Policy',
  'privacy.securityHeading': 'Data Security',
  'privacy.securityBody': 'Your data is stored securely. We do not collect, transmit, or share your personal information with any third party.',
  'privacy.controlHeading': 'Your Control',
  'privacy.controlBody': 'You can clear all stored data at any time by clearing your browser\'s local storage.',
  'privacy.storageHeading': 'Content Storage',
  'privacy.storageBody': 'Poem content you create is stored both locally and on our servers for synchronization across devices.',
  'privacy.thirdPartyHeading': 'Third-Party Services',
  'privacy.thirdPartyBody': 'We use Supabase for authentication and data storage. Please refer to Supabase\'s privacy policy for more details.',
  'about.title': 'About',
  'about.missionHeading': 'Our Mission',
  'about.missionBody': 'From the verses of prehistoric and ancient times to the poems written tonight, we carry humanity\'s literature forward — and connect like-minded readers to share real books through Blend.',
  'about.historyHeading': 'The History Library',
  'about.historyBody': 'Browse 150+ passages from the greatest works of all time — the Bible, the Quran, the Odyssey, the Iliad, the Bhagavad Gita, the Tao Te Ching, Shakespeare, Milton, Dante, and the world\'s poets — all public domain and unexpurgated.',
  'about.blendHeading': 'Blend',
  'about.blendBody': 'Blend is our book exchange. List a book on your shelf, search for the book you want, and request it from a nearby reader. Books travel the world, one reader at a time.',
  'about.safetyHeading': 'Stay Safe',
  'about.safetyBody': 'Never share personal information, and always strictly follow the Privacy Policy when exchanging books or messaging other readers.',

  // settings
  'settings.title': 'Settings',
  'settings.language': 'Language',
  'settings.theme': 'Theme',
  'settings.location': 'Location',
  'settings.notSet': 'Not set',
  'settings.save': 'Save',
  'settings.default': 'Default',

  // location
  'location.selectCountry': 'Select your country',
  'location.zipRequired': 'ZIP / Postal code is required for Blend',
  'location.stateMissing': 'State is missing — check your PIN code or enter it manually',
  'location.title': 'Your Location',
  'location.intro': 'Add your location so Blend can connect you with nearby readers. Your ZIP / Postal code is required and your state will be detected automatically.',
  'location.saving': 'Saving...',
  'location.save': 'Save',
  'location.zipPlaceholder': 'ZIP / PIN code',
  'location.detectingState': 'Detecting state from PIN code...',
  'location.detectFailed': 'Auto-detect failed for this code — enter your state manually.',
  'location.statePlaceholder': 'State / Region',
  'location.autoDetected': '· auto-detected',
  'location.detecting': 'Detecting your location...',
  'location.detectedHeading': 'Location detected automatically',
  'location.autoDetectedValue': 'Auto-detected',
  'location.change': 'Change',
  'location.detectButton': 'Detect automatically',
  'location.detectingEllipsis': 'Detecting…',
  'location.accessDenied': 'Couldn\'t access your location — enter your country and state manually.',
  'location.selectCountryPlaceholder': 'Select country',

  // language
  'language.title': 'Languages',
  'language.empty': 'No languages available. Set your country in Settings.',
  'language.welcome': 'Welcome to Poetry',
  'language.selectCountrySub': 'Select your country to choose a language',
  'language.searchCountry': 'Search your country...',
  'language.noCountries': 'No countries match your search',
  'language.chooseLanguage': 'Choose your language',
  'language.backToCountries': '← Back to countries',

  // header
  'header.backToInbox': 'Back to inbox',
  'header.conversation': 'Conversation',
  'header.revealedAfterApprove': 'Profile revealed after they approve',
  'header.viewProfile': 'View profile',
  'header.clearSearch': 'Clear search',
  'header.closeSearch': 'Close search',
  'header.searchPoems': 'Search poems or poets...',
  'header.searchFavorites': 'Search your favourite lines...',
  'header.searchBooks': 'Search books to borrow...',
  'header.searchingBooks': 'Searching books...',
  'header.noResultsFor': 'No results for "{query}"',
  'header.viewNotification': 'View notification',

  // announcement
  'announcement.typeLogo': 'Logo',
  'announcement.typeAnnouncement': 'Announcement',
  'announcement.typeNote': 'Note',
  'announcement.typeError': 'Error',
  'announcement.typeBug': 'Bug',
  'announcement.typeFixed': 'Fixed',
  'announcement.close': 'Close announcement',

  // changelog
  'changelog.title': 'Changelog',
  'changelog.features': 'Features',
  'changelog.bugFixes': 'Bug Fixes',

  // peers
  'peer.awaitingResponse': 'Awaiting response',
  'peer.accepted': 'Accepted',
  'peer.declined': 'Declined',
  'peer.readerNearby': 'Reader nearby',
  'peer.request': 'Request',
  'peer.inbox': 'Inbox',

  // vector graph
  'graph.noLocations': 'No nearby locations to map yet — add your location in Settings, and make sure a reader\'s location is saved too.',
  'graph.unmappedBook': '{count} book without a mapped location.',
  'graph.unmappedBooks': '{count} books without a mapped location.',
  'graph.you': 'You',

  // auto chat messages
  'msg.shareAgree': 'Yes, I can share "{title}" — I\'m sending it to you.',
  'msg.shareDecline': 'Sorry, I can\'t share "{title}" right now.',
  'msg.receivedConfirm': 'I received "{title}". Thank you!',

  // errors (api)
  'errors.zipNotFound': 'ZIP not found',
  'errors.noStateReturned': 'No state returned',
  'errors.pinNotFound': 'PIN not found',
  'errors.geolocationNotSupported': 'Geolocation not supported',
  'errors.reverseGeocodeFailed': 'Reverse geocode failed',
  'errors.locationPermissionDenied': 'Location permission denied',

  // distance formats
  'dist.lessThanKm': 'less than a km away',
  'dist.kmAway': '~{km} km away',
  'dist.kKmAway': '~{km}k km away',
  'dist.under1Km': '<1 km',
  'dist.tildeKm': '~{km} km',
  'dist.tildeKkm': '~{km}k km',

  // incoming notices (dashboard)
  'notice.newBookRequest': 'New book request',
  'notice.bookShared': 'Book shared',
  'notice.shareDeclined': 'Share declined',
  'notice.bookReceived': 'Book received',
  'notice.newMessage': 'New message',
  'notice.fromSender': '{label} from {sender}',
}

/* ── Language packages (overrides on top of EN) ──
   Add a key to a package to translate it; any key not present falls back to
   English. Codes not listed here fall back to English entirely.
*/
export const LANGUAGE_PACKAGES = {
  ml: {
    'common.loading': 'ലോഡിംഗ്…',
    'common.loadingShort': 'ലോഡിംഗ്',
    'common.back': 'പിന്നോട്ട്',
    'common.close': 'അടയ്ക്കുക',
    'common.save': 'സംരക്ഷിക്കുക',
    'common.cancel': 'റദ്ദാക്കുക',
    'common.next': 'അടുത്തത്',
    'common.continue': 'തുടരുക',
    'common.yes': 'അതെ',
    'common.no': 'ഇല്ല',
    'common.notYet': 'ഇതുവരെ ഇല്ല',
    'common.search': 'തിരയുക',
    'common.retry': 'വീണ്ടും ശ്രമിക്കുക',
    'common.change': 'മാറ്റുക',
    'common.send': 'അയയ്ക്കുക',
    'common.edit': 'തിരുത്തുക',
    'common.delete': 'നീക്കം ചെയ്യുക',
    'common.view': 'കാണുക',
    'common.unknown': 'അറിയില്ല',
    'common.you': 'നിങ്ങൾ',
    'common.anonymous': 'അജ്ഞാതൻ',
    'common.reader': 'വായനക്കാരൻ',
    'common.default': 'സ്ഥിരം',
    'common.poem': 'കവിത',
    'common.poems': 'കവിതകൾ',
    'common.book': 'പുസ്തകം',
    'common.books': 'പുസ്തകങ്ങൾ',
    'common.day': 'ദിവസം',
    'common.days': 'ദിവസങ്ങൾ',
  'common.share': 'പങ്കിടുക',
  'common.byAuthor': 'എഴുതിയത് {author}',
  'common.update': 'അപ്ഡേറ്റ്',
  'common.cachedOffline': 'കാഷെ ചെയ്ത ഡാറ്റ — ഓഫ്‌ലൈൻ',
  'common.syncedServer': 'സെർവറുമായി സമന്വയിപ്പിച്ചു',
    'nav.home': 'ഹോം',
    'nav.read': 'വായന',
    'nav.writings': 'എന്റെ കവിതകൾ',
    'nav.writeNow': 'ഇപ്പോൾ എഴുതുക',
    'nav.writeNew': 'പുതിയത് എഴുതുക',
    'nav.writeAPoem': 'ഒരു കവിത എഴുതുക',
    'nav.favorites': 'പ്രിയപ്പെട്ടവ',
    'nav.favoriteLines': 'പ്രിയ വരികൾ',
    'nav.blend': 'ബ്ലെൻഡ്',
    'nav.inbox': 'ഇൻബോക്സ്',
    'nav.shelf': 'എന്റെ ഷെൽഫ്',
    'nav.notifications': 'അറിയിപ്പുകൾ',
    'nav.settings': 'ക്രമീകരണങ്ങൾ',
    'nav.terms': 'നിബന്ധനകൾ',
    'nav.privacy': 'സ്വകാര്യതാ നയം',
    'nav.about': 'കുറിച്ച്',
    'nav.changelog': 'മാറ്റങ്ങളുടെ രേഖ',
    'nav.categories': 'വിഭാഗങ്ങൾ',
    'nav.findYourBook': 'നിങ്ങളുടെ പുസ്തകം കണ്ടെത്തുക',
    'nav.addYourBooks': 'നിങ്ങളുടെ പുസ്തകങ്ങൾ ചേർക്കുക',
    'nav.latestMessages': 'ഏറ്റവും പുതിയ സന്ദേശങ്ങൾ',
    'nav.menu': 'മെനു',
    'nav.profile': 'പ്രൊഫൈൽ',
    'auth.poetry': 'കവിത',
    'auth.welcomeBack': 'തിരികെ സ്വാഗതം, കവി',
    'auth.join': 'കവിതയിൽ ചേരുക',
    'auth.username': 'ഉപയോക്തൃനാമം',
    'auth.enterUsername': 'ഉപയോക്തൃനാമം നൽകുക',
    'auth.password': 'പാസ്‌വേഡ്',
    'auth.enterPassword': 'പാസ്‌വേഡ് നൽകുക',
    'auth.signingIn': 'പ്രവേശിക്കുന്നു...',
    'auth.signIn': 'പ്രവേശിക്കുക',
    'auth.createAccount': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    'auth.forgotPassword': 'പാസ്‌വേഡ് മറന്നോ?',
    'auth.fillAllFields': 'എല്ലാ ഫീൽഡുകളും പൂരിപ്പിക്കുക',
    'auth.chooseUsername': 'ഒരു അദ്വിതീയ ഉപയോക്തൃനാമം തിരഞ്ഞെടുക്കുക',
    'auth.setupProfile': 'നിങ്ങളുടെ പ്രൊഫൈൽ സജ്ജമാക്കുക',
    'auth.setSecurityQuestion': 'ഒരു സുരക്ഷാ ചോദ്യം സജ്ജമാക്കുക',
    'auth.usernamePlaceholder': 'ഉപയോക്തൃനാമം തിരഞ്ഞെടുക്കുക (കുറഞ്ഞത് 3 അക്ഷരം)',
    'auth.checking': 'പരിശോധിക്കുന്നു...',
    'auth.available': '✓ ലഭ്യം',
    'auth.taken': '✗ എടുത്തിരിക്കുന്നു',
    'auth.suggestions': 'നിർദ്ദേശങ്ങൾ:',
    'auth.alreadyHaveAccount': 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    'auth.displayName': 'പേര്',
    'auth.howOthersSeeYou': 'മറ്റുള്ളവർ നിങ്ങളെ കാണുന്ന രീതി',
    'auth.min6Chars': 'കുറഞ്ഞത് 6 അക്ഷരം',
    'auth.retypePassword': 'പാസ്‌വേഡ് വീണ്ടും നൽകുക',
    'auth.reenterPassword': 'പാസ്‌വേഡ് വീണ്ടും നൽകുക',
    'auth.securityQuestion': 'സുരക്ഷാ ചോദ്യം',
    'auth.securityQuestionExample': 'ഉദാ: നിങ്ങളുടെ ആദ്യത്തെ വളർത്തുമൃഗത്തിന്റെ പേര് എന്തായിരുന്നു?',
    'auth.yourAnswer': 'നിങ്ങളുടെ ഉത്തരം',
    'auth.enterYourAnswer': 'നിങ്ങളുടെ ഉത്തരം നൽകുക',
    'auth.creating': 'സൃഷ്ടിക്കുന്നു...',
    'auth.createAccountBtn': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    'auth.enterYourDisplayName': 'നിങ്ങളുടെ പേര് നൽകുക',
    'auth.passwordMin6': 'പാസ്‌വേഡ് കുറഞ്ഞത് 6 അക്ഷരങ്ങൾ ആയിരിക്കണം',
    'auth.passwordsDontMatch': 'പാസ്‌വേഡുകൾ തമ്മിൽ പൊരുത്തപ്പെടുന്നില്ല',
    'auth.fillBothFields': 'രണ്ട് ഫീൽഡുകളും പൂരിപ്പിക്കുക',
    'auth.enterUsernameToFind': 'നിങ്ങളുടെ അക്കൗണ്ട് കണ്ടെത്താൻ ഉപയോക്തൃനാമം നൽകുക',
    'auth.answerYourSecurityQuestion': 'നിങ്ങളുടെ സുരക്ഷാ ചോദ്യത്തിന് ഉത്തരം നൽകുക',
    'auth.chooseNewPassword': 'ഒരു പുതിയ പാസ്‌വേഡ് തിരഞ്ഞെടുക്കുക',
    'auth.yourUsername': 'നിങ്ങളുടെ ഉപയോക്തൃനാമം',
    'auth.lookingUp': 'തിരയുന്നു...',
    'auth.findAccount': 'അക്കൗണ്ട് കണ്ടെത്തുക',
    'auth.securityQuestionColon': 'സുരക്ഷാ ചോദ്യം:',
    'auth.yourAnswerShort': 'നിങ്ങളുടെ ഉത്തരം',
    'auth.checkingEllipsis': 'പരിശോധിക്കുന്നു...',
    'auth.verifyAnswer': 'ഉത്തരം സ്ഥിരീകരിക്കുക',
    'auth.newPasswordMin6': 'പുതിയ പാസ്‌വേഡ് (കുറഞ്ഞത് 6 അക്ഷരം)',
    'auth.resetting': 'പുനഃക്രമീകരിക്കുന്നു...',
    'auth.resetPassword': 'പാസ്‌വേഡ് പുനഃക്രമീകരിക്കുക',
    'auth.forgotPasswordHeading': 'പാസ്‌വേഡ് മറന്നോ',
    'auth.backToSignIn': 'പ്രവേശനത്തിലേക്ക് മടങ്ങുക',
    'auth.enterUsernameToFindSecurity': 'നിങ്ങളുടെ സുരക്ഷാ ചോദ്യം കണ്ടെത്താൻ ഉപയോക്തൃനാമം നൽകുക.',
    'auth.resetSuccess': 'പാസ്‌വേഡ് പുനഃക്രമീകരിച്ചു. പുതിയ പാസ്‌വേഡുമായി പ്രവേശിക്കുക.',
    'auth.resetNeedsBackend': 'പാസ്‌വേഡ് പുനഃക്രമീകരണത്തിന് എഡ്ജ് ഫംഗ്ഷനുകൾ വിന്യസിക്കണം. ഇപ്പോൾ സുപാബേസ് ഡാഷ്ബോർഡ് ഉപയോഗിക്കുക.',
    'auth.accountCreated': 'അക്കൗണ്ട് സൃഷ്ടിച്ചു! താഴെ പ്രവേശിക്കുക.',
    'auth.usernameMin3': 'ഉപയോക്തൃനാമം കുറഞ്ഞത് 3 അക്ഷരങ്ങൾ ആയിരിക്കണം',
    'auth.usernameCheckFail': 'ഉപയോക്തൃനാമം പരിശോധിക്കാനായില്ല — വീണ്ടും ശ്രമിക്കുക.',
    'auth.usernameTaken': 'ഉപയോക്തൃനാമം എടുത്തിരിക്കുന്നു — താഴെ നിന്ന് ശ്രമിക്കുക',
    'auth.fillSecurityQA': 'സുരക്ഷാ ചോദ്യവും ഉത്തരവും പൂരിപ്പിക്കുക',
    'auth.usernameNotFound': 'ഉപയോക്തൃനാമം കണ്ടെത്തിയില്ല',
    'auth.answerTheSecurityQuestion': 'സുരക്ഷാ ചോദ്യത്തിന് ഉത്തരം നൽകുക',
    'auth.throttle': 'വീണ്ടും ശ്രമിക്കുന്നതിന് മുമ്പ് കുറച്ച് നിമിഷം കാത്തിരിക്കുക.',
    'auth.tooManySignups': 'നിരവധി സൈനപ്പുകൾ. 1 മിനിറ്റ് കാത്തിരുന്ന് വീണ്ടും ശ്രമിക്കുക.',
    'auth.usernameTakenErr': 'ഉപയോക്തൃനാമം ഇതിനകം എടുത്തിരിക്കുന്നു',
    'auth.invalidCredentials': 'അസാധുവായ ഉപയോക്തൃനാമം അല്ലെങ്കിൽ പാസ്‌വേഡ്',
    'auth.noSecurityQuestion': 'ഈ ഉപയോക്താവിന് സുരക്ഷാ ചോദ്യം കണ്ടെത്തിയില്ല',
    'auth.enterUsernameErr': 'നിങ്ങളുടെ ഉപയോക്തൃനാമം നൽകുക',
    'auth.enterAnswerErr': 'നിങ്ങളുടെ ഉത്തരം നൽകുക',
    'auth.createAccountPrompt': 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ? പ്രവേശിക്കുക',
    'auth.stepChooseUsername': 'ഉപയോക്തൃനാമം തിരഞ്ഞെടുക്കുക',
    'auth.stepSetYourName': 'നിങ്ങളുടെ പേര് സജ്ജമാക്കുക',
    'auth.stepSetLocation': 'സ്ഥാനം സജ്ജമാക്കുക',
    'auth.stepSetPassword': 'പാസ്‌വേഡ് സജ്ജമാക്കുക',
    'auth.stepSecurityQuestion': 'സുരക്ഷാ ചോദ്യം',
    'auth.progressUsername': 'ഉപയോക്തൃനാമം',
    'auth.progressName': 'പേര്',
    'auth.progressLocation': 'സ്ഥാനം',
    'auth.progressPassword': 'പാസ്‌വേഡ്',
    'auth.progressSecurity': 'സുരക്ഷ',
    'auth.whatShouldWeCallYou': 'നിങ്ങളെ എന്ത് വിളിക്കണം?',
    'auth.locationRequired': 'നിങ്ങളുടെ സ്ഥാനം ആവശ്യമാണ് — ഇത് സ്വയം കണ്ടെത്തുന്നു, അല്ലെങ്കിൽ രാജ്യം തിരഞ്ഞെടുത്ത് ZIP / PIN കോഡ് നൽകുക.',
    'auth.passwordMin6Chars': 'പാസ്‌വേഡ് (കുറഞ്ഞത് 6 അക്ഷരം)',
    'auth.retypePasswordLower': 'പാസ്‌വേഡ് വീണ്ടും നൽകുക',
    'auth.securityQuestionPlaceholder': 'സുരക്ഷാ ചോദ്യം (പാസ്‌വേഡ് പുനഃക്രമീകരണത്തിന്)',
    'auth.securityAnswer': 'സുരക്ഷാ ഉത്തരം',
    'auth.userFallback': 'ഉപയോക്താവ്',
    'auth.securityDataNotFound': 'സുരക്ഷാ വിവരങ്ങൾ കണ്ടെത്തിയില്ല',
  'auth.signOut': 'ലോഗ് ഔട്ട്',
    'dashboard.needBook': 'പുസ്തകം വേണോ?',
    'dashboard.blendPromo': 'ഇവിടെ ക്ലിക്ക് ചെയ്ത് നിങ്ങൾ തിരയുന്നതിന്റെ ഒരു പകർപ്പ് ആരുടെ കൈയിലുണ്ടായിരിക്കുമെന്ന് കണ്ടെത്തുക.',
    'dashboard.booksNearYou': 'നിങ്ങൾക്ക് സമീപമുള്ള പുസ്തകങ്ങൾ',
    'dashboard.openBlend': 'ബ്ലെൻഡ് തുറക്കുക →',
    'dashboard.identitiesPrivate': 'ഒരു വായനക്കാരൻ നിങ്ങളുടെ അഭ്യർത്ഥന സ്വീകരിക്കുന്നതുവരെ ഐഡന്റിറ്റികൾ സ്വകാര്യമായി തുടരും.',
    'dashboard.status': 'നില →',
    'dashboard.favoriteLine': 'പ്രിയ വരി',
    'dashboard.swipeCard': 'ബ്രൗസ് ചെയ്യാൻ കാർഡ് സ്വൈപ്പ് ചെയ്യുക',
    'dashboard.welcomeBack': 'തിരികെ സ്വാഗതം,',
    'dashboard.welcomeTo': '{site} ലേക്ക് സ്വാഗതം',
    'dashboard.welcomeHeading': 'ബ്ലെൻഡിലേക്ക് സ്വാഗതം',
    'dashboard.welcomeSubtitle': 'സ്വതന്ത്രവും ചരിത്രപരവുമായ സാഹിത്യത്തിന്റെ ശേഖരം',
    'dashboard.welcomeTagline': 'ബ്ലെൻഡ് സമീപത്തുള്ള അപരിചിതർക്ക് പുസ്തകങ്ങൾ പങ്കിടാൻ നിങ്ങളെ അനുവദിക്കുന്നു',
    'dashboard.welcomeFeatureRead': 'ചരിത്രപരവും സ്വതന്ത്ര കവിതയും വായിക്കുക',
    'dashboard.welcomeFeatureShare': 'സമീപത്തുള്ള വായനക്കാരുമായി പുസ്തകങ്ങൾ പങ്കിടുക',
    'dashboard.welcomeFeatureDiscover': 'പുതിയ ശബ്ദങ്ങളും വരികളും കണ്ടെത്തുക',
    'dashboard.discoverCreate': 'കണ്ടെത്തുക & സൃഷ്ടിക്കുക',
    'dashboard.signInToSave': 'സംരക്ഷിക്കാൻ പ്രവേശിക്കുക',
    'dashboard.users': 'ഉപയോക്താക്കൾ',
    'dashboard.active': 'സജീവം',
    'dashboard.writings': 'കവിതകൾ',
    'dashboard.independentWritings': 'സ്വതന്ത്ര കവിതകൾ',
    'dashboard.onlineNow': 'ഇപ്പോൾ ഓൺലൈൻ',
    'dashboard.newsletterEntries': 'വാർത്താക്കുറിപ്പ് എൻട്രികൾ',
    'dashboard.historicCount': '{count} ചരിത്രപരം',
    'dashboard.heroMission': 'പുരാതന കാലത്തെ കവിതകൾ മുതൽ ഇന്ന് രാത്രി എഴുതിയ കവിതകൾ വരെ, ഞങ്ങൾ മനുഷ്യരാശിയുടെ സാഹിത്യം മുന്നോട്ട് കൊണ്ടുപോകുന്നു — കൂടാതെ ബ്ലെൻഡിലൂടെ യഥാർത്ഥ പുസ്തകങ്ങൾ പങ്കിടാൻ സമാന ചിന്താഗതിക്കാരായ വായനക്കാരുമായി നിങ്ങളെ ബന്ധിപ്പിക്കുന്നു.',
    'dashboard.heroSafety': 'സുരക്ഷിതമായിരിക്കുക: വ്യക്തിഗത വിവരങ്ങൾ ഒരിക്കലും പങ്കിടരുത്, കൂടാതെ സ്വകാര്യതാ നയം എപ്പോഴും കർശനമായി പാലിക്കുക.',
    'dashboard.joinNewsletter': 'വാർത്താക്കുറിപ്പിൽ ചേരുക',
    'dashboard.newsletterBlurb': 'നിങ്ങളുടെ മെയിലിലൂടെ ദിവസേനയുള്ള തിരഞ്ഞെടുത്ത ജ്ഞാനം — എല്ലാ ദിവസവും ഒരു ചിന്താപൂർവ്വമായ വരിയും കുറിപ്പും.',
    'dashboard.newsletterSuccess': 'നിങ്ങൾ രജിസ്റ്റർ ചെയ്തു! നാളെ നിങ്ങളുടെ ഇൻബോക്സ് കാണുക.',
    'dashboard.emailPlaceholder': 'you@example.com',
    'dashboard.joining': 'ചേരുന്നു…',
    'dashboard.join': 'ചേരുക',
    'dashboard.newsletterFailed': 'ഇപ്പോൾ സബ്സ്ക്രൈബ് ചെയ്യാൻ കഴിഞ്ഞില്ല. വീണ്ടും ശ്രമിക്കുക.',
    'dashboard.recentlyViewed': 'അടുത്തിടെ കണ്ടവ',
    'dashboard.trendingPoems': 'ജനപ്രിയ കവിതകൾ',
    'dashboard.latestPoems': 'ഏറ്റവും പുതിയ കവിതകൾ',
    'dashboard.by': '{author} എഴുതിയത്',
    'dashboard.myWritings': 'എന്റെ കവിതകൾ',
    'dashboard.new': '+ പുതിയത്',
    'dashboard.noWritingsTap': 'ഇതുവരെ കവിതകൾ ഇല്ല. ആദ്യ കവിത എഴുതാൻ + ടാപ്പ് ചെയ്യുക.',
    'dashboard.viewAllWritings': 'എല്ലാം കാണുക {count} കവിതകൾ →',
    'dashboard.startReading': 'വായന ആരംഭിക്കുക',
    'dashboard.swipeToExplore': 'പര്യവേക്ഷണം ചെയ്യാൻ സ്വൈപ്പ് ചെയ്യുക',
    'poetry.noMorePoems': 'മറ്റ് കവിതകളില്ല',
    'poetry.tapToRead': 'മുഴുവൻ കവിത വായിക്കാൻ ടാപ്പ് ചെയ്യുക →',
    'poetry.historic': 'പഴയത്',
    'poetry.readFullPoem': 'മുഴുവൻ കവിത വായിക്കുക',
    'poetry.collapse': 'ചുരുക്കുക',
    'poetry.noPoemSelected': 'കവിത തിരഞ്ഞെടുത്തിട്ടില്ല',
    'poetry.swipeSideways': 'മാറാൻ വശങ്ങളിലേക്ക് സ്വൈപ്പ് ചെയ്യുക',
    'poetry.swipe': 'സ്വൈപ്പ് ചെയ്യുക',
    'poetry.lines': '{count} വരികൾ',
    'poetry.titlePlaceholder': 'കവിതയുടെ തലക്കെട്ട്...',
    'poetry.bodyPlaceholder': 'നിങ്ങളുടെ കവിത ഇവിടെ എഴുതുക...',
    'poetry.categories': 'വിഭാഗങ്ങൾ (പരമാവധി {count}):',
    'poetry.historicNotRatable': 'ചരിത്രപരമായ കവിത · റേറ്റിംഗ് സാധ്യമല്ല',
    'poetry.tapToSaveFavorite': 'പ്രിയപ്പെട്ടതായി സംരക്ഷിക്കാൻ ഒരു വരിയിൽ ടാപ്പ് ചെയ്യുക',
    'poetry.swipeOr': 'സ്വൈപ്പ് ചെയ്യുക അല്ലെങ്കിൽ',
    'poetry.prev': 'മുമ്പ്',
    'poetry.next': 'അടുത്തത്',
    'poetry.editPoem': 'കവിത തിരുത്തുക',
    'poetry.writeAPoem': 'ഒരു കവിത എഴുതുക',
    'poetry.update': 'അപ്ഡേറ്റ് ചെയ്യുക',
    'poetry.save': 'സംരക്ഷിക്കുക',
    'poetry.titleYourPoem': 'നിങ്ങളുടെ കവിതയ്ക്ക് തലക്കെട്ട് നൽകുക...',
    'poetry.untitled': 'ശീർഷകമില്ലാത്തത്',
    'category.love': 'പ്രണയം',
    'category.nature': 'പ്രകൃതി',
    'category.philosophy': 'തത്വശാസ്ത്രം',
    'category.tragedy': 'ദുരന്തം',
    'category.hope': 'പ്രതീക്ഷ',
    'category.spirituality': 'ആത്മീയത',
    'category.freedom': 'സ്വാതന്ത്ര്യം',
    'category.war': 'യുദ്ധം',
    'category.death': 'മരണം',
    'category.joy': 'ആനന്ദം',
    'category.reflection': 'ചിന്ത',
    'category.fantasy': 'ഫാന്റസി',
    'categories.title': 'വിഭാഗങ്ങൾ',
    'categories.empty': 'വിഭാഗങ്ങൾ ലഭ്യമല്ല.',
    'categories.noPoems': 'ഈ വിഭാഗത്തിൽ കവിതകൾ ഇല്ല.',
    'blend.couldNotLoad': 'സമീപത്തെ പുസ്തകങ്ങൾ ലോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല — വീണ്ടും ശ്രമിക്കുക.',
    'blend.searchFailed': 'തിരയൽ പരാജയപ്പെട്ടു — വീണ്ടും ശ്രമിക്കുക.',
    'blend.signInToRequest': 'ഒരു പുസ്തകം അഭ്യർത്ഥിക്കാൻ പ്രവേശിക്കുക',
    'blend.requestMessage': 'ഹായ്, എനിക്ക് "{title}" വായിക്കാൻ താൽപ്പര്യമുണ്ട്, ദയവായി പങ്കിടാമോ.',
    'blend.requestSent': '"{title}" നായി സമീപത്തെ ഒരു വായനക്കാരന് അഭ്യർത്ഥന അയച്ചു',
    'blend.searchPlaceholder': 'തലക്കെട്ട് അല്ലെങ്കിൽ രചയിതാവ് വഴി പുസ്തകം തിരയുക…',
    'blend.yourBlend': 'നിങ്ങളുടെ ബ്ലെൻഡ്',
    'blend.requestThisBook': 'ഈ പുസ്തകം അഭ്യർത്ഥിക്കുക',
    'blend.emptyState': 'ഒരു പുസ്തകം കണ്ടെത്താൻ മുകളിലെ തിരയൽ ബാർ ഉപയോഗിക്കുക — അത് ഉള്ള സമീപത്തെ വായനക്കാരെ കണ്ടെത്തുക.',
    'blend.emptySubtext': 'നിങ്ങളുടെ പുസ്തകങ്ങൾ ലോകം ചുറ്റും, ഒരു വായനക്കാരൻ ഒരിക്കൽ.',
    'blend.findingBooks': 'നിങ്ങൾക്ക് സമീപം പുസ്തകങ്ങൾ കണ്ടെത്തുന്നു...',
    'blend.noBooks': 'ഇതുവരെ പുസ്തകങ്ങൾ ലിസ്റ്റ് ചെയ്തിട്ടില്ല. പേര് വഴി തിരയാൻ ശ്രമിക്കുക, അല്ലെങ്കിൽ നിങ്ങളുടെ ഷെൽഫിൽ ഒരു പുസ്തകം ചേർക്കുക.',
    'blend.selfOnly': 'ഈ പുസ്തകം നിങ്ങളുടെ ഷെൽഫിൽ ഉണ്ട്, എന്നാൽ സമീപത്ത് മറ്റ് വായനക്കാർ ഇത് ലിസ്റ്റ് ചെയ്തിട്ടില്ല.',
    'blend.resultFound': '{count} പുസ്തകം "{query}" നായി കണ്ടെത്തി',
    'blend.resultsFound': '{count} പുസ്തകങ്ങൾ "{query}" നായി കണ്ടെത്തി',
    'blend.ongoingBlend': '{count} നടന്നുകൊണ്ടിരിക്കുന്ന ബ്ലെൻഡ്',
    'blend.ongoingBlends': '{count} നടന്നുകൊണ്ടിരിക്കുന്ന ബ്ലെൻഡുകൾ',
    'blend.noOngoing': 'ഇതുവരെ നടന്നുകൊണ്ടിരിക്കുന്ന ബ്ലെൻഡുകൾ ഇല്ല. മുകളിൽ തിരയുക അല്ലെങ്കിൽ "നിങ്ങൾക്ക് സമീപമുള്ള പുസ്തകങ്ങൾ" എന്നതിന് കീഴിൽ ഒരു പുസ്തകം ടാപ്പ് ചെയ്യുക.',
    'blend.readerHidden': 'വായനക്കാരന്റെ വിശദാംശങ്ങൾ മറഞ്ഞിരിക്കും — ഇൻബോക്സിൽ അവർ നിങ്ങളുടെ അഭ്യർത്ഥന സ്വീകരിച്ചതിന് ശേഷം മാത്രമേ പങ്കിടൂ.',
    'blend.awaitingResponse': 'പ്രതികരണത്തിനായി കാത്തിരിക്കുന്നു',
    'blend.accepted': 'സ്വീകരിച്ചു',
    'blend.declined': 'നിരസിച്ചു',
    'blend.readerNearby': 'സമീപത്തെ വായനക്കാരൻ',
    'shelf.empty': 'സൗജന്യമായി പ്രചരിപ്പിക്കാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്ന പുസ്തകങ്ങൾ ചേർക്കുക.',
    'shelf.emptySubtext': 'അത് തിരികെ വരാം അല്ലെങ്കിൽ വരില്ല, പക്ഷേ അത് തീർച്ചയായും ലോകത്തിനിടയിൽ സഞ്ചരിക്കും.',
    'shelf.addBook': 'ഒരു പുസ്തകം ചേർക്കുക',
    'shelf.titlePlaceholder': 'തലക്കെട്ട് *',
    'shelf.subtitlePlaceholder': 'ഉപശീർഷകം (ഓപ്ഷണൽ)',
    'shelf.pageCountPlaceholder': 'പേജ് കൗണ്ട്',
    'shelf.authorPlaceholder': 'രചയിതാവ് *',
    'shelf.summaryPlaceholder': 'പുസ്തകത്തെക്കുറിച്ചുള്ള സംഗ്രഹം (ഓപ്ഷണൽ)',
    'shelf.addToShelf': 'ഷെൽഫിലേക്ക് ചേർക്കുക',
    'shelf.trackExchange': 'എക്സ്ചേഞ്ച് ട്രാക്കിംഗ്',
    'shelf.markAsSent': 'അയച്ചതായി അടയാളപ്പെടുത്തുക',
    'shelf.sentConfirm': 'നിങ്ങൾ പുസ്തകം അയച്ചിട്ടുണ്ടോ?',
    'shelf.yesSent': 'അതെ, അയച്ചു',
    'shelf.notYet': 'ഇതുവരെ ഇല്ല',
    'shelf.sent': 'അയച്ചു ✓',
    'shelf.yesReceived': 'അതെ, ലഭിച്ചു',
    'shelf.receivedComplete': 'ലഭിച്ചു ✓ - കൈമാറ്റം പൂർത്തിയായി',
    'shelf.removeFromShelf': 'ഷെൽഫിൽ നിന്ന് നീക്കം ചെയ്യുക',
    'shelf.addAnother': '+ മറ്റൊരു പുസ്തകം ചേർക്കുക',
  'shelf.pages': '{count} പേജുകൾ',
  'shelf.available': 'ലഭ്യമാണ്',
  'shelf.inTransit': 'വഴിയിലാണ്',
    'inbox.bookRequest': 'പുസ്തക അഭ്യർത്ഥന',
    'inbox.shared': 'പങ്കിട്ടു',
    'inbox.sharedWithYou': 'നിങ്ങളുമായി പങ്കിട്ടു',
    'inbox.declined': 'നിരസിച്ചു',
    'inbox.received': 'ലഭിച്ചു',
    'inbox.exchangeComplete': 'എക്സ്ചേഞ്ച് പൂർത്തിയായി',
    'inbox.sharePrompt': '{contact} "{title}" കടം വാങ്ങാൻ ആഗ്രഹിക്കുന്നു. പങ്കിടാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുണ്ടോ?',
    'inbox.receivePrompt': '{contact} "{title}" നിങ്ങളുമായി പങ്കിട്ടു. നിങ്ങൾക്കത് ലഭിച്ചോ?',
    'inbox.messagePlaceholder': 'സന്ദേശം...',
    'inbox.empty': 'ഇതുവരെ സംഭാഷണങ്ങൾ ഇല്ല.',
    'inbox.emptyHint': 'ഒരു സംഭാഷണം ആരംഭിക്കാൻ ബ്ലെൻഡിലൂടെ ഒരു പുസ്തകം അഭ്യർത്ഥിക്കുക.',
    'inbox.replySent': 'മറുപടി {contact} ന് അയച്ചു',
    'inbox.re': 'മറുപടി: {title}',
    'inbox.agreedShare': 'നിങ്ങൾ "{title}" {contact} നുമായി പങ്കിടാൻ സമ്മതിച്ചു',
    'inbox.declinedShare': 'നിങ്ങൾ "{title}" പങ്കിടൽ നിരസിച്ചു',
    'inbox.addedToShelf': '"{title}" നിങ്ങളുടെ ഷെൽഫിൽ ചേർത്തു',
    'inbox.notYetReceived': 'ഇതുവരെ ലഭിച്ചിട്ടില്ല.',
    'inbox.markedNotReceived': 'ഇതുവരെ ലഭിച്ചിട്ടില്ലെന്ന് അടയാളപ്പെടുത്തി',
    'profile.title': 'പ്രൊഫൈൽ',
    'profile.writings': 'കവിതകൾ',
    'profile.favorites': 'പ്രിയപ്പെട്ടവ',
    'profile.shelf': 'ഷെൽഫ്',
    'profile.streak': 'സ്ട്രീക്ക്',
    'profile.shelfBooks': '({count} പുസ്തകങ്ങൾ)',
    'profile.addYourBooks': '(നിങ്ങളുടെ പുസ്തകങ്ങൾ ചേർക്കുക)',
    'profile.findYourBook': '(നിങ്ങളുടെ പുസ്തകം കണ്ടെത്തുക)',
    'profile.myWritingsCount': 'എന്റെ കവിതകൾ ({count})',
    'profile.favoriteLinesCount': 'പ്രിയ വരികൾ ({count})',
    'profile.notifications': 'അറിയിപ്പുകൾ',
    'profile.couldNotLoad': 'ഈ പ്രൊഫൈൽ ലോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല — വീണ്ടും ശ്രമിക്കുക.',
    'profile.loading': 'പ്രൊഫൈൽ ലോഡ് ചെയ്യുന്നു...',
    'profile.noReader': '"@{username}" ന് വായനക്കാരനെ കണ്ടെത്തിയില്ല.',
    'profile.readingStreak': 'വായന സ്ട്രീക്ക്',
    'profile.bestStreak': 'മികച്ച സ്ട്രീക്ക്',
    'profile.streakDay': '{count} ദിവസം',
    'profile.streakDays': '{count} ദിവസങ്ങൾ',
    'profile.favoriteLines': 'പ്രിയ വരികൾ',
    'profile.noFavoritesShared': 'ഇതുവരെ പ്രിയ വരികൾ പങ്കിട്ടിട്ടില്ല.',
    'profile.bookshelfCount': 'ബുക്ക്ഷെൽഫ് ({count})',
    'profile.noBooks': 'ഇതുവരെ ഷെൽഫിൽ പുസ്തകങ്ങൾ ഇല്ല.',
    'profile.recentlyRead': 'അടുത്തിടെ വായിച്ചവ',
    'profile.noRecent': 'ഇതുവരെ സമീപകാല വായനകൾ ഇല്ല.',
    'profile.frequentlyRead': 'പതിവായി വായിച്ചവ',
    'profile.noPatterns': 'ഇതുവരെ വായന രീതികൾ ഇല്ല.',
    'profile.readCount': '{count}x',
    'notifications.clearAll': 'എല്ലാം മായ്ക്കുക',
    'notifications.title': 'അറിയിപ്പുകൾ',
    'notifications.empty': 'അറിയിപ്പുകൾ ഇല്ല.',
    'notifications.dailyFavoritesTitle': 'ദൈനംദിന പ്രിയപ്പെട്ട വരി ഓർമ്മപ്പെടുത്തൽ',
    'notifications.dailyFavoritesOne': 'നിങ്ങൾക്ക് 1 പ്രിയപ്പെട്ട വരി ഉണ്ട് — ഇന്ന് വായിക്കൂ.',
    'notifications.dailyFavoritesMany': 'നിങ്ങൾക്ക് {count} പ്രിയപ്പെട്ട വരികൾ ഉണ്ട് — ഇന്ന് വായിക്കൂ.',
    'notifications.newRequest': '"{title}" എന്ന പുസ്തകത്തിനായി {from} ൽ നിന്ന് പുതിയ ബ്ലെൻഡ് അഭ്യർത്ഥന',
    'notifications.newMessage': '{from} ൽ നിന്ന് പുതിയ സന്ദേശം',
    'favorites.clearAll': 'എല്ലാം മായ്ക്കുക',
    'favorites.empty': 'ഇതുവരെ പ്രിയ വരികൾ ഇല്ല.',
    'favorites.hint': 'വായിക്കുമ്പോൾ ഒരു വരി മൂന്ന് തവണ ടാപ്പ് ചെയ്താൽ അത് പ്രിയപ്പെട്ടതായി സംരക്ഷിക്കപ്പെടും.',
    'favorites.attribution': '— {poem} {author} എഴുതിയത്',
    'favorites.shareQuote': 'ഈ ഉദ്ധരണി പങ്കിടുക',
    'favorites.previousPage': 'മുമ്പത്തെ പേജ്',
    'favorites.nextPage': 'അടുത്ത പേജ്',
    'favorites.pageOf': 'പേജ് {page} / {count}',
    'writings.empty': 'ഇതുവരെ കവിതകൾ ഇല്ല.',
    'writings.cta': 'നിങ്ങളുടെ ആദ്യ കവിത എഴുതുക',
  'writings.writePoem': 'ഒരു കവിത എഴുതുക',
  'writings.editPoem': 'കവിത തിരുത്തുക',
  'writings.titlePlaceholder': 'നിങ്ങളുടെ കവിതയ്ക്ക് തലക്കെട്ട്...',
  'writings.contentPlaceholder': 'ഇവിടെ കവിത എഴുതുക...',
  'writings.categoriesHint': 'വിഭാഗങ്ങൾ (പരമാവധി {count}):',
    'terms.title': 'നിബന്ധനകളും വ്യവസ്ഥകളും',
    'terms.acceptanceHeading': 'നിബന്ധനകളുടെ അംഗീകാരം',
    'terms.acceptanceBody': 'Poetry ഉപയോഗിക്കുന്നതിലൂടെ, നിങ്ങൾ ഈ നിബന്ധനകൾ അംഗീകരിക്കുന്നു. പങ്കിടുന്ന എല്ലാ കവിതകളും അതത് രചയിതാക്കളുടെ ബൗദ്ധിക സ്വത്താണ്.',
    'terms.disclaimerHeading': 'സേവന നിരാകരണം',
    'terms.disclaimerBody': 'ഈ സേവനം "ഉള്ളതുപോലെ" വാറന്റികളില്ലാതെ നൽകുന്നു. ഈ നിബന്ധനകൾ ഏത് സമയത്തും അപ്ഡേറ്റ് ചെയ്യാനുള്ള അവകാശം ഞങ്ങളിൽ നിക്ഷിപ്തമാണ്.',
    'terms.responsibilitiesHeading': 'ഉപയോക്തൃ ഉത്തരവാദിത്തങ്ങൾ',
    'terms.responsibilitiesBody': 'നിങ്ങൾ പ്രസിദ്ധീകരിക്കുന്ന ഉള്ളടക്കത്തിന് നിങ്ങൾ മാത്രമാണ് ഉത്തരവാദി. നിയമവിരുദ്ധമോ ദോഷകരമോ പകർപ്പവകാശം ലംഘിക്കുന്നതോ ആയ വസ്തുക്കൾ പോസ്റ്റ് ചെയ്യുന്നത് വിലക്കപ്പെട്ട പ്രവർത്തനങ്ങളിൽ ഉൾപ്പെടുന്നു.',
    'terms.terminationHeading': 'അവസാനിപ്പിക്കൽ',
    'terms.terminationBody': 'ഈ നിബന്ധനകൾ ലംഘിക്കുന്നതിന് ഞങ്ങൾക്ക് ആക്സസ് താൽക്കാലികമായി നിർത്തുകയോ അവസാനിപ്പിക്കുകയോ ചെയ്യാം.',
    'privacy.title': 'സ്വകാര്യതാ നയം',
    'privacy.securityHeading': 'ഡാറ്റ സുരക്ഷ',
    'privacy.securityBody': 'നിങ്ങളുടെ ഡാറ്റ സുരക്ഷിതമായി സൂക്ഷിക്കുന്നു. ഞങ്ങൾ നിങ്ങളുടെ വ്യക്തിഗത വിവരങ്ങൾ ശേഖരിക്കുകയോ കൈമാറുകയോ ഏതെങ്കിലും മൂന്നാം കക്ഷിയുമായി പങ്കിടുകയോ ചെയ്യുന്നില്ല.',
    'privacy.controlHeading': 'നിങ്ങളുടെ നിയന്ത്രണം',
    'privacy.controlBody': 'നിങ്ങളുടെ ബ്രൗസറിന്റെ ലോക്കൽ സ്റ്റോറേജ് മായ്ച്ചുകൊണ്ട് ഏത് സമയത്തും എല്ലാ സംഭരിച്ച ഡാറ്റയും മായ്ക്കാം.',
    'privacy.storageHeading': 'ഉള്ളടക്ക സംഭരണം',
    'privacy.storageBody': 'നിങ്ങൾ സൃഷ്ടിക്കുന്ന കവിത ഉള്ളടക്കം ഉപകരണങ്ങളിലുടനീളം സമന്വയത്തിനായി പ്രാദേശികമായും ഞങ്ങളുടെ സെർവറുകളിലും സൂക്ഷിക്കുന്നു.',
    'privacy.thirdPartyHeading': 'മൂന്നാം കക്ഷി സേവനങ്ങൾ',
    'privacy.thirdPartyBody': 'ആധികാരികതയ്ക്കും ഡാറ്റ സംഭരണത്തിനും ഞങ്ങൾ Supabase ഉപയോഗിക്കുന്നു. കൂടുതൽ വിശദാംശങ്ങൾക്ക് Supabase-ന്റെ സ്വകാര്യതാ നയം കാണുക.',
    'about.title': 'കുറിച്ച്',
    'about.missionHeading': 'ഞങ്ങളുടെ ദൗത്യം',
    'about.missionBody': 'പുരാതന കാലത്തെ കവിതകൾ മുതൽ ഇന്ന് രാത്രി എഴുതിയ കവിതകൾ വരെ, ഞങ്ങൾ മനുഷ്യരാശിയുടെ സാഹിത്യം മുന്നോട്ട് കൊണ്ടുപോകുന്നു — ബ്ലെൻഡിലൂടെ യഥാർത്ഥ പുസ്തകങ്ങൾ പങ്കിടാൻ സമാന ചിന്താഗതിക്കാരായ വായനക്കാരുമായി ബന്ധിപ്പിക്കുന്നു.',
    'about.historyHeading': 'ചരിത്ര ലൈബ്രറി',
    'about.historyBody': 'എല്ലാ കാലത്തെയും മികച്ച കൃതികളിൽ നിന്നുള്ള 150+ ഭാഗങ്ങൾ ബ്രൗസ് ചെയ്യുക — ബൈബിൾ, ഖുർആൻ, ഒഡീസി, ഇലിയാഡ്, ഭഗവദ്ഗീത, താവോ തേ ചിംഗ്, ഷേക്സ്പിയർ, മിൽട്ടൺ, ദാന്തെ, ലോകത്തിലെ കവികൾ — എല്ലാം പൊതു സ്വത്തും വെട്ടിച്ചുരുക്കാത്തതും.',
    'about.blendHeading': 'ബ്ലെൻഡ്',
    'about.blendBody': 'ബ്ലെൻഡ് ഞങ്ങളുടെ പുസ്തക കൈമാറ്റമാണ്. നിങ്ങളുടെ ഷെൽഫിൽ ഒരു പുസ്തകം ലിസ്റ്റ് ചെയ്യുക, നിങ്ങൾക്ക് വേണ്ട പുസ്തകം തിരയുക, സമീപത്തെ ഒരു വായനക്കാരനിൽ നിന്ന് അത് അഭ്യർത്ഥിക്കുക. പുസ്തകങ്ങൾ ലോകം ചുറ്റുന്നു, ഒരു വായനക്കാരൻ ഒരിക്കൽ.',
    'about.safetyHeading': 'സുരക്ഷിതമായിരിക്കുക',
    'about.safetyBody': 'വ്യക്തിഗത വിവരങ്ങൾ ഒരിക്കലും പങ്കിടരുത്, പുസ്തകങ്ങൾ കൈമാറുമ്പോഴോ മറ്റ് വായനക്കാരുമായി സന്ദേശമയയ്ക്കുമ്പോഴോ എപ്പോഴും സ്വകാര്യതാ നയം കർശനമായി പാലിക്കുക.',
    'settings.title': 'ക്രമീകരണങ്ങൾ',
    'settings.language': 'ഭാഷ',
    'settings.theme': 'തീം',
    'settings.location': 'സ്ഥാനം',
    'settings.notSet': 'സജ്ജമാക്കിയിട്ടില്ല',
    'settings.save': 'സംരക്ഷിക്കുക',
    'settings.default': 'സ്ഥിരം',
    'location.selectCountry': 'നിങ്ങളുടെ രാജ്യം തിരഞ്ഞെടുക്കുക',
    'location.zipRequired': 'ബ്ലെൻഡിന് ZIP / പോസ്റ്റൽ കോഡ് ആവശ്യമാണ്',
    'location.stateMissing': 'സംസ്ഥാനം കാണുന്നില്ല — നിങ്ങളുടെ PIN കോഡ് പരിശോധിക്കുക അല്ലെങ്കിൽ സ്വയം നൽകുക',
    'location.title': 'നിങ്ങളുടെ സ്ഥാനം',
    'location.intro': 'ബ്ലെൻഡിന് നിങ്ങളെ സമീപത്തെ വായനക്കാരുമായി ബന്ധിപ്പിക്കാൻ നിങ്ങളുടെ സ്ഥാനം ചേർക്കുക. നിങ്ങളുടെ ZIP / പോസ്റ്റൽ കോഡ് ആവശ്യമാണ്, നിങ്ങളുടെ സംസ്ഥാനം സ്വയം കണ്ടെത്തപ്പെടും.',
    'location.saving': 'സംരക്ഷിക്കുന്നു...',
    'location.save': 'സംരക്ഷിക്കുക',
    'location.zipPlaceholder': 'ZIP / PIN കോഡ്',
    'location.detectingState': 'PIN കോഡിൽ നിന്ന് സംസ്ഥാനം കണ്ടെത്തുന്നു...',
    'location.detectFailed': 'ഈ കോഡിനായി സ്വയം കണ്ടെത്തൽ പരാജയപ്പെട്ടു — സംസ്ഥാനം സ്വയം നൽകുക.',
    'location.statePlaceholder': 'സംസ്ഥാനം / പ്രദേശം',
    'location.autoDetected': '· സ്വയം കണ്ടെത്തി',
    'location.detecting': 'നിങ്ങളുടെ സ്ഥാനം കണ്ടെത്തുന്നു...',
    'location.detectedHeading': 'സ്ഥാനം സ്വയം കണ്ടെത്തി',
    'location.autoDetectedValue': 'സ്വയം കണ്ടെത്തിയത്',
    'location.change': 'മാറ്റുക',
    'location.detectButton': 'സ്വയം കണ്ടെത്തുക',
    'location.detectingEllipsis': 'കണ്ടെത്തുന്നു…',
    'location.accessDenied': 'നിങ്ങളുടെ സ്ഥാനം ആക്സസ് ചെയ്യാൻ കഴിഞ്ഞില്ല — രാജ്യവും സംസ്ഥാനവും സ്വയം നൽകുക.',
    'location.selectCountryPlaceholder': 'രാജ്യം തിരഞ്ഞെടുക്കുക',
    'language.title': 'ഭാഷകൾ',
    'language.empty': 'ഭാഷകൾ ലഭ്യമല്ല. ക്രമീകരണങ്ങളിൽ നിങ്ങളുടെ രാജ്യം സജ്ജമാക്കുക.',
    'language.welcome': 'Poetry ലേക്ക് സ്വാഗതം',
    'language.selectCountrySub': 'ഒരു ഭാഷ തിരഞ്ഞെടുക്കാൻ നിങ്ങളുടെ രാജ്യം തിരഞ്ഞെടുക്കുക',
    'language.searchCountry': 'നിങ്ങളുടെ രാജ്യം തിരയുക...',
    'language.noCountries': 'നിങ്ങളുടെ തിരയലുമായി പൊരുത്തപ്പെടുന്ന രാജ്യങ്ങൾ ഇല്ല',
    'language.chooseLanguage': 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
    'language.backToCountries': '← രാജ്യങ്ങളിലേക്ക് മടങ്ങുക',
    'header.backToInbox': 'ഇൻബോക്സിലേക്ക് മടങ്ങുക',
    'header.conversation': 'സംഭാഷണം',
    'header.revealedAfterApprove': 'അവർ അംഗീകരിച്ചതിന് ശേഷം പ്രൊഫൈൽ വെളിപ്പെടും',
    'header.viewProfile': 'പ്രൊഫൈൽ കാണുക',
    'header.clearSearch': 'തിരയൽ മായ്ക്കുക',
    'header.closeSearch': 'തിരയൽ അടയ്ക്കുക',
    'header.searchPoems': 'കവിതകളോ കവികളോ തിരയുക...',
    'header.searchFavorites': 'നിങ്ങളുടെ പ്രിയ വരികൾ തിരയുക...',
    'header.searchBooks': 'കടം വാങ്ങാൻ പുസ്തകങ്ങൾ തിരയുക...',
    'header.searchingBooks': 'പുസ്തകങ്ങൾ തിരയുന്നു...',
    'header.noResultsFor': '"{query}" നായി ഫലങ്ങളില്ല',
    'header.viewNotification': 'അറിയിപ്പ് കാണുക',
    'announcement.typeLogo': 'ലോഗോ',
    'announcement.typeAnnouncement': 'അറിയിപ്പ്',
    'announcement.typeNote': 'കുറിപ്പ്',
    'announcement.typeError': 'പിശക്',
    'announcement.typeBug': 'ബഗ്',
    'announcement.typeFixed': 'പരിഹരിച്ചു',
    'announcement.close': 'അറിയിപ്പ് അടയ്ക്കുക',
    'changelog.title': 'മാറ്റങ്ങളുടെ രേഖ',
    'changelog.features': 'സവിശേഷതകൾ',
    'changelog.bugFixes': 'ബഗ് പരിഹാരങ്ങൾ',
    'peer.awaitingResponse': 'പ്രതികരണത്തിനായി കാത്തിരിക്കുന്നു',
    'peer.accepted': 'സ്വീകരിച്ചു',
    'peer.declined': 'നിരസിച്ചു',
    'peer.readerNearby': 'സമീപത്തെ വായനക്കാരൻ',
    'peer.request': 'അഭ്യർത്ഥന',
  'peer.inbox': 'ഇൻബോക്സ്',
    'graph.noLocations': 'ഇതുവരെ മാപ്പ് ചെയ്യാൻ സമീപത്തെ ലൊക്കേഷനുകൾ ഇല്ല — ക്രമീകരണങ്ങളിൽ നിങ്ങളുടെ സ്ഥാനം ചേർക്കുക, ഒരു വായനക്കാരന്റെ സ്ഥാനവും സംരക്ഷിച്ചിട്ടുണ്ടെന്ന് ഉറപ്പാക്കുക.',
    'graph.unmappedBook': '{count} പുസ്തകത്തിന് മാപ്പ് ചെയ്ത ലൊക്കേഷൻ ഇല്ല.',
    'graph.unmappedBooks': '{count} പുസ്തകങ്ങൾക്ക് മാപ്പ് ചെയ്ത ലൊക്കേഷൻ ഇല്ല.',
    'graph.you': 'നിങ്ങൾ',
    'msg.shareAgree': 'അതെ, എനിക്ക് "{title}" പങ്കിടാം — ഞാൻ നിങ്ങൾക്ക് അയയ്ക്കുന്നു.',
    'msg.shareDecline': 'ക്ഷമിക്കണം, എനിക്ക് ഇപ്പോൾ "{title}" പങ്കിടാൻ കഴിയില്ല.',
    'msg.receivedConfirm': 'എനിക്ക് "{title}" ലഭിച്ചു. നന്ദി!',
    'errors.zipNotFound': 'ZIP കണ്ടെത്തിയില്ല',
    'errors.noStateReturned': 'സംസ്ഥാനം ലഭിച്ചില്ല',
    'errors.pinNotFound': 'PIN കണ്ടെത്തിയില്ല',
    'errors.geolocationNotSupported': 'ജിയോലൊക്കേഷൻ പിന്തുണയ്ക്കുന്നില്ല',
    'errors.reverseGeocodeFailed': 'റിവേഴ്സ് ജിയോകോഡ് പരാജയപ്പെട്ടു',
    'errors.locationPermissionDenied': 'ലൊക്കേഷൻ അനുമതി നിരസിച്ചു',
    'dist.lessThanKm': 'ഒരു കിലോമീറ്ററിൽ താഴെ അകലെ',
    'dist.kmAway': '~{km} കിലോമീറ്റർ അകലെ',
    'dist.kKmAway': '~{km}k കിലോമീറ്റർ അകലെ',
    'dist.under1Km': '<1 കിലോമീറ്റർ',
    'dist.tildeKm': '~{km} കിലോമീറ്റർ',
    'dist.tildeKkm': '~{km}k കിലോമീറ്റർ',
    'notice.newBookRequest': 'പുതിയ പുസ്തക അഭ്യർത്ഥന',
    'notice.bookShared': 'പുസ്തകം പങ്കിട്ടു',
    'notice.shareDeclined': 'പങ്കിടൽ നിരസിച്ചു',
    'notice.bookReceived': 'പുസ്തകം ലഭിച്ചു',
    'notice.newMessage': 'പുതിയ സന്ദേശം',
    'notice.fromSender': '{sender} ൽ നിന്ന് {label}',
  },

  hi: {
    'common.loading': 'लोड हो रहा है...',
    'common.loadingShort': 'लोड हो रहा है',
    'common.back': 'वापस',
    'common.close': 'बंद करें',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.next': 'आगे',
    'common.continue': 'जारी रखें',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
    'common.notYet': 'अभी नहीं',
    'common.search': 'खोजें',
    'common.retry': 'पुनः प्रयास करें',
    'common.change': 'बदलें',
    'common.send': 'भेजें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएँ',
    'common.view': 'देखें',
    'common.unknown': 'अज्ञात',
    'common.you': 'आप',
    'common.anonymous': 'गुमनाम',
    'common.reader': 'पाठक',
    'common.default': 'डिफ़ॉल्ट',
    'common.poem': 'कविता',
    'common.poems': 'कविताएँ',
    'common.book': 'किताब',
    'common.books': 'किताबें',
    'common.day': 'दिन',
    'common.days': 'दिन',
  'common.share': 'शेयर करें',
  'common.byAuthor': 'द्वारा {author}',
  'common.update': 'अपडेट करें',
  'common.cachedOffline': 'कैश किया गया डेटा — ऑफ़लाइन',
  'common.syncedServer': 'सर्वर से सिंक किया गया',
    'nav.home': 'होम',
    'nav.read': 'पढ़ें',
    'nav.writings': 'मेरी रचनाएँ',
    'nav.writeNow': 'अभी लिखें',
    'nav.writeNew': 'नई लिखें',
    'nav.writeAPoem': 'कविता लिखें',
    'nav.favorites': 'पसंदीदा',
    'nav.favoriteLines': 'पसंदीदा पंक्तियाँ',
    'nav.blend': 'ब्लेंड',
    'nav.inbox': 'इनबॉक्स',
    'nav.shelf': 'मेरी शेल्फ़',
    'nav.notifications': 'सूचनाएँ',
    'nav.settings': 'सेटिंग्स',
    'nav.terms': 'शर्तें',
    'nav.privacy': 'गोपनीयता नीति',
    'nav.about': 'परिचय',
    'nav.changelog': 'बदलाव',
    'nav.categories': 'श्रेणियाँ',
    'nav.findYourBook': 'अपनी किताब खोजें',
    'nav.addYourBooks': 'अपनी किताबें जोड़ें',
    'nav.latestMessages': 'नवीनतम संदेश',
    'nav.menu': 'मेनू',
    'nav.profile': 'प्रोफ़ाइल',
    'auth.poetry': 'कविता',
    'auth.welcomeBack': 'वापसी पर स्वागत है, कवि',
    'auth.join': 'कविता से जुड़ें',
    'auth.username': 'उपयोगकर्ता नाम',
    'auth.enterUsername': 'उपयोगकर्ता नाम दर्ज करें',
    'auth.password': 'पासवर्ड',
    'auth.enterPassword': 'पासवर्ड दर्ज करें',
    'auth.signingIn': 'साइन इन हो रहा है...',
    'auth.signIn': 'साइन इन',
    'auth.createAccount': 'खाता बनाएँ',
    'auth.forgotPassword': 'पासवर्ड भूल गए?',
    'auth.fillAllFields': 'सभी फ़ील्ड भरें',
    'auth.chooseUsername': 'एक अनोखा उपयोगकर्ता नाम चुनें',
    'auth.setupProfile': 'अपनी प्रोफ़ाइल सेट करें',
    'auth.setSecurityQuestion': 'सुरक्षा प्रश्न सेट करें',
    'auth.usernamePlaceholder': 'उपयोगकर्ता नाम चुनें (न्यूनतम 3 अक्षर)',
    'auth.checking': 'जाँच हो रही है...',
    'auth.available': '✓ उपलब्ध',
    'auth.taken': '✗ लिया गया',
    'auth.suggestions': 'सुझाव:',
    'auth.alreadyHaveAccount': 'पहले से खाता है?',
    'auth.displayName': 'प्रदर्शन नाम',
    'auth.howOthersSeeYou': 'दूसरे आपको कैसे देखते हैं',
    'auth.min6Chars': 'न्यूनतम 6 अक्षर',
    'auth.retypePassword': 'पासवर्ड फिर से दर्ज करें',
    'auth.reenterPassword': 'पासवर्ड फिर से दर्ज करें',
    'auth.securityQuestion': 'सुरक्षा प्रश्न',
    'auth.securityQuestionExample': 'जैसे: आपके पहले पालतू जानवर का नाम क्या था?',
    'auth.yourAnswer': 'आपका उत्तर',
    'auth.enterYourAnswer': 'अपना उत्तर दर्ज करें',
    'auth.creating': 'बनाया जा रहा है...',
    'auth.createAccountBtn': 'खाता बनाएँ',
    'auth.enterYourDisplayName': 'अपना नाम दर्ज करें',
    'auth.passwordMin6': 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
    'auth.passwordsDontMatch': 'पासवर्ड मेल नहीं खाते',
    'auth.fillBothFields': 'दोनों फ़ील्ड भरें',
    'auth.enterUsernameToFind': 'अपना खाता खोजने के लिए उपयोगकर्ता नाम दर्ज करें',
    'auth.answerYourSecurityQuestion': 'अपने सुरक्षा प्रश्न का उत्तर दें',
    'auth.chooseNewPassword': 'नया पासवर्ड चुनें',
    'auth.yourUsername': 'आपका उपयोगकर्ता नाम',
    'auth.lookingUp': 'खोजा जा रहा है...',
    'auth.findAccount': 'खाता खोजें',
    'auth.securityQuestionColon': 'सुरक्षा प्रश्न:',
    'auth.yourAnswerShort': 'आपका उत्तर',
    'auth.checkingEllipsis': 'जाँच हो रही है...',
    'auth.verifyAnswer': 'उत्तर सत्यापित करें',
    'auth.newPasswordMin6': 'नया पासवर्ड (न्यूनतम 6 अक्षर)',
    'auth.resetting': 'रीसेट हो रहा है...',
    'auth.resetPassword': 'पासवर्ड रीसेट करें',
    'auth.forgotPasswordHeading': 'पासवर्ड भूल गए',
    'auth.backToSignIn': 'साइन इन पर वापस',
    'auth.enterUsernameToFindSecurity': 'अपना सुरक्षा प्रश्न खोजने के लिए उपयोगकर्ता नाम दर्ज करें।',
    'auth.resetSuccess': 'पासवर्ड रीसेट हो गया। अपने नए पासवर्ड से साइन इन करें।',
    'auth.resetNeedsBackend': 'पासवर्ड रीसेट के लिए एज फंक्शन तैनात होने चाहिए। अभी सुपाबेस डैशबोर्ड का उपयोग करें।',
    'auth.accountCreated': 'खाता बन गया! नीचे साइन इन करें।',
    'auth.usernameMin3': 'उपयोगकर्ता नाम कम से कम 3 अक्षर का होना चाहिए',
    'auth.usernameCheckFail': 'उपयोगकर्ता नाम जाँचा नहीं जा सका — कृपया पुनः प्रयास करें।',
    'auth.usernameTaken': 'उपयोगकर्ता नाम लिया जा चुका है — नीचे देखें',
    'auth.fillSecurityQA': 'सुरक्षा प्रश्न और उत्तर भरें',
    'auth.usernameNotFound': 'उपयोगकर्ता नाम नहीं मिला',
    'auth.answerTheSecurityQuestion': 'सुरक्षा प्रश्न का उत्तर दें',
    'auth.throttle': 'पुनः प्रयास करने से पहले कुछ सेकंड प्रतीक्षा करें।',
    'auth.tooManySignups': 'बहुत अधिक साइनअप। 1 मिनट प्रतीक्षा करके पुनः प्रयास करें।',
    'auth.usernameTakenErr': 'उपयोगकर्ता नाम पहले से लिया गया है',
    'auth.invalidCredentials': 'अमान्य उपयोगकर्ता नाम या पासवर्ड',
    'auth.noSecurityQuestion': 'इस उपयोगकर्ता के लिए सुरक्षा प्रश्न नहीं मिला',
    'auth.enterUsernameErr': 'अपना उपयोगकर्ता नाम दर्ज करें',
    'auth.enterAnswerErr': 'अपना उत्तर दर्ज करें',
    'auth.createAccountPrompt': 'पहले से खाता है? साइन इन करें',
    'auth.stepChooseUsername': 'उपयोगकर्ता नाम चुनें',
    'auth.stepSetYourName': 'अपना नाम सेट करें',
    'auth.stepSetLocation': 'स्थान सेट करें',
    'auth.stepSetPassword': 'पासवर्ड सेट करें',
    'auth.stepSecurityQuestion': 'सुरक्षा प्रश्न',
    'auth.progressUsername': 'उपयोगकर्ता नाम',
    'auth.progressName': 'नाम',
    'auth.progressLocation': 'स्थान',
    'auth.progressPassword': 'पासवर्ड',
    'auth.progressSecurity': 'सुरक्षा',
    'auth.whatShouldWeCallYou': 'हम आपको क्या कहें?',
    'auth.locationRequired': 'आपका स्थान आवश्यक है — यह स्वतः पता चल जाता है, या अपना देश चुनकर ZIP / PIN कोड दर्ज करें।',
    'auth.passwordMin6Chars': 'पासवर्ड (न्यूनतम 6 अक्षर)',
    'auth.retypePasswordLower': 'पासवर्ड फिर से दर्ज करें',
    'auth.securityQuestionPlaceholder': 'सुरक्षा प्रश्न (पासवर्ड रीसेट के लिए)',
    'auth.securityAnswer': 'सुरक्षा उत्तर',
    'auth.userFallback': 'उपयोगकर्ता',
    'auth.securityDataNotFound': 'सुरक्षा डेटा नहीं मिला',
  'auth.signOut': 'साइन आउट',
    'dashboard.needBook': 'किताब चाहिए?',
    'dashboard.blendPromo': 'यहाँ क्लिक करें और पता करें कि आप जो खोज रहे हैं उसकी एक प्रति किसके पास हो सकती है।',
    'dashboard.booksNearYou': 'आपके पास की किताबें',
    'dashboard.openBlend': 'ब्लेंड खोलें →',
    'dashboard.identitiesPrivate': 'जब तक कोई पाठक आपका अनुरोध स्वीकार नहीं करता, पहचान निजी रहती है।',
    'dashboard.status': 'स्थिति →',
    'dashboard.favoriteLine': 'पसंदीदा पंक्ति',
    'dashboard.swipeCard': 'ब्राउज़ करने के लिए कार्ड स्वाइप करें',
    'dashboard.welcomeBack': 'वापसी पर स्वागत है,',
    'dashboard.welcomeTo': '{site} में आपका स्वागत है',
    'dashboard.welcomeHeading': 'ब्लेंडली में आपका स्वागत है',
    'dashboard.welcomeSubtitle': 'स्वतंत्र और ऐतिहासिक साहित्य का भंडार',
    'dashboard.welcomeTagline': 'ब्लेंडली आपको आस-पास के अजनबियों के साथ किताबें साझा करने देता है',
    'dashboard.welcomeFeatureRead': 'ऐतिहासिक और स्वतंत्र कविता पढ़ें',
    'dashboard.welcomeFeatureShare': 'निकटतम पाठकों के साथ किताबें साझा करें',
    'dashboard.welcomeFeatureDiscover': 'नई आवाज़ें और पंक्तियाँ खोजें',
    'dashboard.discoverCreate': 'खोजें और बनाएँ',
    'dashboard.signInToSave': 'सहेजने के लिए साइन इन करें',
    'dashboard.users': 'उपयोगकर्ता',
    'dashboard.active': 'सक्रिय',
    'dashboard.writings': 'रचनाएँ',
    'dashboard.independentWritings': 'स्वतंत्र रचनाएँ',
    'dashboard.onlineNow': 'अभी ऑनलाइन',
    'dashboard.newsletterEntries': 'न्यूज़लेटर प्रविष्टियाँ',
    'dashboard.historicCount': '{count} ऐतिहासिक',
    'dashboard.heroMission': 'प्रागैतिहासिक और प्राचीन काल की पंक्तियों से लेकर आज रात लिखी गई कविताओं तक, हम मानवता के साहित्य को आगे बढ़ाते हैं — और ब्लेंड के माध्यम से वास्तविक किताबें साझा करने के लिए आपको समान सोच वाले पाठकों से जोड़ते हैं।',
    'dashboard.heroSafety': 'सुरक्षित रहें: व्यक्तिगत जानकारी कभी साझा न करें, और हमेशा गोपनीयता नीति का सख्ती से पालन करें।',
    'dashboard.joinNewsletter': 'न्यूज़लेटर से जुड़ें',
    'dashboard.newsletterBlurb': 'आपके मेल में चुनिंदा दैनिक ज्ञान — हर दिन एक विचारशील पंक्ति और नोट।',
    'dashboard.newsletterSuccess': 'आप शामिल हैं! कल अपना इनबॉक्स देखें।',
    'dashboard.emailPlaceholder': 'you@example.com',
    'dashboard.joining': 'जुड़ रहे हैं…',
    'dashboard.join': 'जुड़ें',
    'dashboard.newsletterFailed': 'अभी सदस्यता नहीं ली जा सकी। कृपया पुनः प्रयास करें।',
    'dashboard.recentlyViewed': 'हाल ही में देखी गईं',
    'dashboard.trendingPoems': 'ट्रेंडिंग कविताएँ',
    'dashboard.latestPoems': 'नवीनतम कविताएँ',
    'dashboard.by': '{author} द्वारा',
    'dashboard.myWritings': 'मेरी रचनाएँ',
    'dashboard.new': '+ नई',
    'dashboard.noWritingsTap': 'अभी तक कोई रचना नहीं। पहली कविता लिखने के लिए + टैप करें।',
    'dashboard.viewAllWritings': 'सभी {count} रचनाएँ देखें →',
    'dashboard.startReading': 'पढ़ना शुरू करें',
    'dashboard.swipeToExplore': 'खोजने के लिए स्वाइप करें',
    'poetry.noMorePoems': 'और कोई कविता नहीं',
    'poetry.tapToRead': 'पूरी कविता पढ़ने के लिए टैप करें →',
    'poetry.historic': 'पुरानी',
    'poetry.readFullPoem': 'पूरी कविता पढ़ें',
    'poetry.collapse': 'छोटा करें',
    'poetry.noPoemSelected': 'कोई कविता चयनित नहीं',
    'poetry.swipeSideways': 'बदलने के लिए बगल में स्वाइप करें',
    'poetry.swipe': 'स्वाइप करें',
    'poetry.lines': '{count} पंक्तियाँ',
    'poetry.titlePlaceholder': 'कविता का शीर्षक...',
    'poetry.bodyPlaceholder': 'अपनी कविता यहाँ लिखें...',
    'poetry.categories': 'श्रेणियाँ (अधिकतम {count}):',
    'poetry.historicNotRatable': 'ऐतिहासिक कविता · रेटिंग संभव नहीं',
    'poetry.tapToSaveFavorite': 'पसंदीदा के रूप में सहेजने के लिए किसी पंक्ति पर टैप करें',
    'poetry.swipeOr': 'स्वाइप करें या',
    'poetry.prev': 'पिछला',
    'poetry.next': 'आगे',
    'poetry.editPoem': 'कविता संपादित करें',
    'poetry.writeAPoem': 'कविता लिखें',
    'poetry.update': 'अपडेट करें',
    'poetry.save': 'सहेजें',
    'poetry.titleYourPoem': 'अपनी कविता को शीर्षक दें...',
    'poetry.untitled': 'बिना शीर्षक',
    'category.love': 'प्रेम',
    'category.nature': 'प्रकृति',
    'category.philosophy': 'दर्शन',
    'category.tragedy': 'त्रासदी',
    'category.hope': 'आशा',
    'category.spirituality': 'आध्यात्मिकता',
    'category.freedom': 'स्वतंत्रता',
    'category.war': 'युद्ध',
    'category.death': 'मृत्यु',
    'category.joy': 'आनंद',
    'category.reflection': 'चिंतन',
    'category.fantasy': 'कल्पना',
    'categories.title': 'श्रेणियाँ',
    'categories.empty': 'कोई श्रेणी उपलब्ध नहीं।',
    'categories.noPoems': 'इस श्रेणी में कोई कविता नहीं।',
    'blend.couldNotLoad': 'आस-पास की किताबें लोड नहीं हो सकीं — कृपया पुनः प्रयास करें।',
    'blend.searchFailed': 'खोज विफल रही — पुनः प्रयास करें।',
    'blend.signInToRequest': 'किताब अनुरोध करने के लिए साइन इन करें',
    'blend.requestMessage': 'नमस्ते, मुझे "{title}" पढ़ने में रुचि है, क्या आप कृपया साझा कर सकते हैं।',
    'blend.requestSent': '"{title}" के लिए पास के पाठक को अनुरोध भेजा गया',
    'blend.searchPlaceholder': 'शीर्षक या लेखक से किताब खोजें…',
    'blend.yourBlend': 'आपका ब्लेंड',
    'blend.requestThisBook': 'यह किताब अनुरोध करें',
    'blend.emptyState': 'किताब खोजने के लिए ऊपर सर्च बार का उपयोग करें — पास के पाठक खोजें जिनके पास वह है।',
    'blend.emptySubtext': 'आपकी किताबें दुनिया में यात्रा करती हैं, एक पाठक के बाद एक।',
    'blend.findingBooks': 'आपके पास की किताबें खोजी जा रही हैं...',
    'blend.noBooks': 'अभी तक कोई किताब सूचीबद्ध नहीं। नाम से खोजने का प्रयास करें, या अपनी शेल्फ़ में किताब जोड़ें।',
    'blend.selfOnly': 'यह किताब आपकी शेल्फ़ पर है, लेकिन पास में किसी अन्य पाठक ने इसे सूचीबद्ध नहीं किया है।',
    'blend.resultFound': '{count} किताब "{query}" के लिए मिली',
    'blend.resultsFound': '{count} किताबें "{query}" के लिए मिलीं',
    'blend.ongoingBlend': '{count} चल रहा ब्लेंड',
    'blend.ongoingBlends': '{count} चल रहे ब्लेंड',
    'blend.noOngoing': 'अभी कोई चल रहा ब्लेंड नहीं। ऊपर खोजें या "आपके पास की किताबें" के अंतर्गत किसी किताब पर टैप करें।',
    'blend.readerHidden': 'पाठक का विवरण छिपा रहता है — इनबॉक्स में अनुरोध स्वीकार करने के बाद ही साझा किया जाता है।',
    'blend.awaitingResponse': 'प्रतिक्रिया की प्रतीक्षा',
    'blend.accepted': 'स्वीकृत',
    'blend.declined': 'अस्वीकृत',
    'blend.readerNearby': 'पास का पाठक',
    'shelf.empty': 'वे किताबें जोड़ें जिन्हें आप मुफ्त में प्रसारित करना चाहते हैं।',
    'shelf.emptySubtext': 'हो सकता है वह लौट आए या न आए, लेकिन वह दुनिया में ज़रूर यात्रा करती है।',
    'shelf.addBook': 'किताब जोड़ें',
    'shelf.titlePlaceholder': 'शीर्षक *',
    'shelf.subtitlePlaceholder': 'उपशीर्षक (वैकल्पिक)',
    'shelf.pageCountPlaceholder': 'पृष्ठ संख्या',
    'shelf.authorPlaceholder': 'लेखक *',
    'shelf.summaryPlaceholder': 'किताब के बारे में सारांश (वैकल्पिक)',
    'shelf.addToShelf': 'शेल्फ़ में जोड़ें',
    'shelf.trackExchange': 'एक्सचेंज ट्रैकिंग',
    'shelf.markAsSent': 'भेजा गया चिह्नित करें',
    'shelf.sentConfirm': 'क्या आपने किताब भेज दी है?',
    'shelf.yesSent': 'हाँ, भेज दी',
    'shelf.notYet': 'अभी नहीं',
    'shelf.sent': 'भेज दिया ✓',
    'shelf.yesReceived': 'हाँ, मिल गई',
    'shelf.receivedComplete': 'मिल गया ✓ - विनिमय पूर्ण',
    'shelf.removeFromShelf': 'शेल्फ़ से हटाएँ',
    'shelf.addAnother': '+ एक और किताब जोड़ें',
  'shelf.pages': '{count} पृष्ठ',
  'shelf.available': 'उपलब्ध',
  'shelf.inTransit': 'रास्ते में',
    'inbox.bookRequest': 'किताब अनुरोध',
    'inbox.shared': 'साझा की गई',
    'inbox.sharedWithYou': 'आपके साथ साझा की गई',
    'inbox.declined': 'अस्वीकृत',
    'inbox.received': 'प्राप्त',
    'inbox.exchangeComplete': 'एक्सचेंज पूर्ण',
    'inbox.sharePrompt': '{contact} "{title}" उधार लेना चाहता है। क्या आप साझा करना चाहते हैं?',
    'inbox.receivePrompt': '{contact} ने "{title}" आपके साथ साझा की। क्या आपको मिली?',
    'inbox.messagePlaceholder': 'संदेश...',
    'inbox.empty': 'अभी कोई बातचीत नहीं।',
    'inbox.emptyHint': 'बातचीत शुरू करने के लिए ब्लेंड के माध्यम से किताब का अनुरोध करें।',
    'inbox.replySent': 'उत्तर {contact} को भेजा गया',
    'inbox.re': 'उत्तर: {title}',
    'inbox.agreedShare': 'आपने "{title}" {contact} के साथ साझा करने पर सहमति दी',
    'inbox.declinedShare': 'आपने "{title}" साझा करने से इनकार कर दिया',
    'inbox.addedToShelf': '"{title}" आपकी शेल्फ़ में जोड़ी गई',
    'inbox.notYetReceived': 'अभी तक प्राप्त नहीं हुई।',
    'inbox.markedNotReceived': 'अभी तक प्राप्त नहीं हुई के रूप में चिह्नित',
    'profile.title': 'प्रोफ़ाइल',
    'profile.writings': 'रचनाएँ',
    'profile.favorites': 'पसंदीदा',
    'profile.shelf': 'शेल्फ़',
    'profile.streak': 'स्ट्रीक',
    'profile.shelfBooks': '({count} किताबें)',
    'profile.addYourBooks': '(अपनी किताबें जोड़ें)',
    'profile.findYourBook': '(अपनी किताब खोजें)',
    'profile.myWritingsCount': 'मेरी रचनाएँ ({count})',
    'profile.favoriteLinesCount': 'पसंदीदा पंक्तियाँ ({count})',
    'profile.notifications': 'सूचनाएँ',
    'profile.couldNotLoad': 'यह प्रोफ़ाइल लोड नहीं हो सकी — पुनः प्रयास करें।',
    'profile.loading': 'प्रोफ़ाइल लोड हो रही है...',
    'profile.noReader': '"@{username}" के लिए कोई पाठक नहीं मिला।',
    'profile.readingStreak': 'पठन स्ट्रीक',
    'profile.bestStreak': 'सर्वश्रेष्ठ स्ट्रीक',
    'profile.streakDay': '{count} दिन',
    'profile.streakDays': '{count} दिन',
    'profile.favoriteLines': 'पसंदीदा पंक्तियाँ',
    'profile.noFavoritesShared': 'अभी तक कोई पसंदीदा पंक्ति साझा नहीं की गई।',
    'profile.bookshelfCount': 'बुकशेल्फ़ ({count})',
    'profile.noBooks': 'अभी शेल्फ़ पर कोई किताब नहीं।',
    'profile.recentlyRead': 'हाल ही में पढ़ी गईं',
    'profile.noRecent': 'अभी कोई हालिया पठन नहीं।',
    'profile.frequentlyRead': 'बार-बार पढ़ी गईं',
    'profile.noPatterns': 'अभी कोई पठन पैटर्न नहीं।',
    'profile.readCount': '{count}x',
    'notifications.clearAll': 'सभी हटाएँ',
    'notifications.title': 'सूचनाएँ',
    'notifications.empty': 'कोई सूचनाएँ नहीं।',
    'notifications.dailyFavoritesTitle': 'दैनिक पसंदीदा अनुस्मारक',
    'notifications.dailyFavoritesOne': 'आपकी 1 पसंदीदा पंक्ति सुरक्षित है — आज इसे पढ़ें।',
    'notifications.dailyFavoritesMany': 'आपकी {count} पसंदीदा पंक्तियाँ सुरक्षित हैं — आज इन्हें पढ़ें।',
    'notifications.newRequest': '{from} से "{title}" के लिए नया ब्लेंड अनुरोध',
    'notifications.newMessage': '{from} से नया संदेश',
    'favorites.clearAll': 'सभी हटाएँ',
    'favorites.empty': 'अभी तक कोई पसंदीदा पंक्ति नहीं।',
    'favorites.hint': 'पढ़ते समय किसी पंक्ति को तीन बार टैप करके उसे पसंदीदा में सहेजें।',
    'favorites.attribution': '— {poem} {author} द्वारा',
    'favorites.shareQuote': 'यह उद्धरण साझा करें',
    'favorites.previousPage': 'पिछला पृष्ठ',
    'favorites.nextPage': 'अगला पृष्ठ',
    'favorites.pageOf': 'पृष्ठ {page} / {count}',
    'writings.empty': 'अभी तक कोई रचना नहीं।',
    'writings.cta': 'अपनी पहली कविता लिखें',
  'writings.writePoem': 'कविता लिखें',
  'writings.editPoem': 'कविता संपादित करें',
  'writings.titlePlaceholder': 'अपनी कविता को शीर्षक दें...',
  'writings.contentPlaceholder': 'अपनी कविता यहाँ लिखें...',
  'writings.categoriesHint': 'श्रेणियाँ (अधिकतम {count}):',
    'terms.title': 'नियम और शर्तें',
    'terms.acceptanceHeading': 'नियमों की स्वीकृति',
    'terms.acceptanceBody': 'कविता का उपयोग करके, आप इन नियमों से सहमत होते हैं। साझा की गई सभी कविताएँ अपने-अपने लेखकों की बौद्धिक संपदा बनी रहती हैं।',
    'terms.disclaimerHeading': 'सेवा अस्वीकरण',
    'terms.disclaimerBody': 'यह सेवा बिना वारंटी के "जैसी है" प्रदान की जाती है। हम किसी भी समय इन नियमों को अद्यतन करने का अधिकार रखते हैं।',
    'terms.responsibilitiesHeading': 'उपयोगकर्ता जिम्मेदारियाँ',
    'terms.responsibilitiesBody': 'आप अपने प्रकाशित सामग्री के लिए पूर्ण रूप से जिम्मेदार हैं। प्रतिबंधित गतिविधियों में अवैध, हानिकारक या साहित्यिक चोरी वाली सामग्री पोस्ट करना शामिल है।',
    'terms.terminationHeading': 'समाप्ति',
    'terms.terminationBody': 'इन नियमों के उल्लंघन के लिए हम पहुँच को निलंबित या समाप्त कर सकते हैं।',
    'privacy.title': 'गोपनीयता नीति',
    'privacy.securityHeading': 'डेटा सुरक्षा',
    'privacy.securityBody': 'आपका डेटा सुरक्षित रूप से संग्रहीत है। हम आपकी व्यक्तिगत जानकारी किसी तीसरे पक्ष के साथ एकत्र, प्रसारित या साझा नहीं करते।',
    'privacy.controlHeading': 'आपका नियंत्रण',
    'privacy.controlBody': 'अपने ब्राउज़र की लोकल स्टोरेज साफ़ करके आप किसी भी समय सभी संग्रहीत डेटा साफ़ कर सकते हैं।',
    'privacy.storageHeading': 'सामग्री भंडारण',
    'privacy.storageBody': 'आपके द्वारा बनाई गई कविता सामग्री उपकरणों में समन्वय के लिए स्थानीय और हमारे सर्वर दोनों पर संग्रहीत होती है।',
    'privacy.thirdPartyHeading': 'तृतीय-पक्ष सेवाएँ',
    'privacy.thirdPartyBody': 'हम प्रमाणीकरण और डेटा भंडारण के लिए Supabase का उपयोग करते हैं। अधिक जानकारी के लिए Supabase की गोपनीयता नीति देखें।',
    'about.title': 'परिचय',
    'about.missionHeading': 'हमारा मिशन',
    'about.missionBody': 'प्रागैतिहासिक और प्राचीन काल की पंक्तियों से लेकर आज रात लिखी गई कविताओं तक, हम मानवता के साहित्य को आगे बढ़ाते हैं — और ब्लेंड के माध्यम से वास्तविक किताबें साझा करने के लिए समान सोच वाले पाठकों से जोड़ते हैं।',
    'about.historyHeading': 'इतिहास पुस्तकालय',
    'about.historyBody': 'हर समय की महानतम कृतियों के 150+ अंश ब्राउज़ करें — बाइबल, कुरान, ओडिसी, इलियड, भगवद गीता, ताओ ते चिंग, शेक्सपियर, मिल्टन, दांते और दुनिया के कवि — सभी सार्वजनिक डोमेन में और असंपादित।',
    'about.blendHeading': 'ब्लेंड',
    'about.blendBody': 'ब्लेंड हमारा पुस्तक विनिमय है। अपनी शेल्फ़ पर किताब सूचीबद्ध करें, जो किताब चाहिए उसे खोजें, और पास के पाठक से अनुरोध करें। किताबें दुनिया में यात्रा करती हैं, एक पाठक के बाद एक।',
    'about.safetyHeading': 'सुरक्षित रहें',
    'about.safetyBody': 'व्यक्तिगत जानकारी कभी साझा न करें, और किताबों के आदान-प्रदान या अन्य पाठकों से संदेश भेजते समय हमेशा गोपनीयता नीति का सख्ती से पालन करें।',
    'settings.title': 'सेटिंग्स',
    'settings.language': 'भाषा',
    'settings.theme': 'थीम',
    'settings.location': 'स्थान',
    'settings.notSet': 'सेट नहीं',
    'settings.save': 'सहेजें',
    'settings.default': 'डिफ़ॉल्ट',
    'location.selectCountry': 'अपना देश चुनें',
    'location.zipRequired': 'ब्लेंड के लिए ZIP / पोस्टल कोड आवश्यक है',
    'location.stateMissing': 'राज्य नहीं मिला — अपना PIN कोड जाँचें या मैन्युअल रूप से दर्ज करें',
    'location.title': 'आपका स्थान',
    'location.intro': 'अपना स्थान जोड़ें ताकि ब्लेंड आपको पास के पाठकों से जोड़ सके। आपका ZIP / पोस्टल कोड आवश्यक है और आपका राज्य स्वतः पता चल जाएगा।',
    'location.saving': 'सहेजा जा रहा है...',
    'location.save': 'सहेजें',
    'location.zipPlaceholder': 'ZIP / PIN कोड',
    'location.detectingState': 'PIN कोड से राज्य का पता लगाया जा रहा है...',
    'location.detectFailed': 'इस कोड के लिए स्वतः पता लगाना विफल रहा — राज्य मैन्युअल रूप से दर्ज करें।',
    'location.statePlaceholder': 'राज्य / क्षेत्र',
    'location.autoDetected': '· स्वतः पता चला',
    'location.detecting': 'आपका स्थान पता लगाया जा रहा है...',
    'location.detectedHeading': 'स्थान स्वतः पता चला',
    'location.autoDetectedValue': 'स्वतः पता चला',
    'location.change': 'बदलें',
    'location.detectButton': 'स्वतः पता लगाएँ',
    'location.detectingEllipsis': 'पता लगाया जा रहा है…',
    'location.accessDenied': 'आपके स्थान तक पहुँच नहीं हो सकी — देश और राज्य मैन्युअल रूप से दर्ज करें।',
    'location.selectCountryPlaceholder': 'देश चुनें',
    'language.title': 'भाषाएँ',
    'language.empty': 'कोई भाषा उपलब्ध नहीं। सेटिंग्स में अपना देश सेट करें।',
    'language.welcome': 'कविता में आपका स्वागत है',
    'language.selectCountrySub': 'भाषा चुनने के लिए अपना देश चुनें',
    'language.searchCountry': 'अपना देश खोजें...',
    'language.noCountries': 'आपकी खोज से मेल खाता कोई देश नहीं',
    'language.chooseLanguage': 'अपनी भाषा चुनें',
    'language.backToCountries': '← देशों पर वापस',
    'header.backToInbox': 'इनबॉक्स पर वापस',
    'header.conversation': 'बातचीत',
    'header.revealedAfterApprove': 'स्वीकृति के बाद प्रोफ़ाइल दिखेगी',
    'header.viewProfile': 'प्रोफ़ाइल देखें',
    'header.clearSearch': 'खोज साफ़ करें',
    'header.closeSearch': 'खोज बंद करें',
    'header.searchPoems': 'कविताएँ या कवि खोजें...',
    'header.searchFavorites': 'अपनी पसंदीदा पंक्तियाँ खोजें...',
    'header.searchBooks': 'उधार लेने के लिए किताबें खोजें...',
    'header.searchingBooks': 'किताबें खोजी जा रही हैं...',
    'header.noResultsFor': '"{query}" के लिए कोई परिणाम नहीं',
    'header.viewNotification': 'सूचना देखें',
    'announcement.typeLogo': 'लोगो',
    'announcement.typeAnnouncement': 'घोषणा',
    'announcement.typeNote': 'नोट',
    'announcement.typeError': 'त्रुटि',
    'announcement.typeBug': 'बग',
    'announcement.typeFixed': 'ठीक किया गया',
    'announcement.close': 'घोषणा बंद करें',
    'changelog.title': 'बदलाव',
    'changelog.features': 'विशेषताएँ',
    'changelog.bugFixes': 'बग सुधार',
    'peer.awaitingResponse': 'प्रतिक्रिया की प्रतीक्षा',
    'peer.accepted': 'स्वीकृत',
    'peer.declined': 'अस्वीकृत',
    'peer.readerNearby': 'पास का पाठक',
    'peer.request': 'अनुरोध',
  'peer.inbox': 'इनबॉक्स',
    'graph.noLocations': 'अभी मैप करने के लिए पास की कोई स्थिति नहीं — सेटिंग्स में अपना स्थान जोड़ें, और सुनिश्चित करें कि पाठक का स्थान भी सहेजा हुआ है।',
    'graph.unmappedBook': '{count} किताब बिना मैप की गई स्थिति के।',
    'graph.unmappedBooks': '{count} किताबें बिना मैप की गई स्थिति के।',
    'graph.you': 'आप',
    'msg.shareAgree': 'हाँ, मैं "{title}" साझा कर सकता हूँ — मैं इसे आपको भेज रहा हूँ।',
    'msg.shareDecline': 'क्षमा करें, मैं अभी "{title}" साझा नहीं कर सकता।',
    'msg.receivedConfirm': 'मुझे "{title}" मिल गई। धन्यवाद!',
    'errors.zipNotFound': 'ZIP नहीं मिला',
    'errors.noStateReturned': 'कोई राज्य नहीं लौटाया गया',
    'errors.pinNotFound': 'PIN नहीं मिला',
    'errors.geolocationNotSupported': 'जियोलोकेशन समर्थित नहीं है',
    'errors.reverseGeocodeFailed': 'रिवर्स जियोकोड विफल',
    'errors.locationPermissionDenied': 'स्थान की अनुमति अस्वीकृत',
    'dist.lessThanKm': 'एक किमी से कम दूर',
    'dist.kmAway': '~{km} किमी दूर',
    'dist.kKmAway': '~{km}k किमी दूर',
    'dist.under1Km': '<1 किमी',
    'dist.tildeKm': '~{km} किमी',
    'dist.tildeKkm': '~{km}k किमी',
    'notice.newBookRequest': 'नया किताब अनुरोध',
    'notice.bookShared': 'किताब साझा की गई',
    'notice.shareDeclined': 'साझाकरण अस्वीकृत',
    'notice.bookReceived': 'किताब प्राप्त हुई',
    'notice.newMessage': 'नया संदेश',
    'notice.fromSender': '{sender} से {label}',
  },
}

/* Get the translation package for a language code (falls back to EN). */
export function getLanguagePackage(code) {
  return LANGUAGE_PACKAGES[code] || {}
}
