export const themes = {
  spring: {
    id: 'spring',
    label: 'Spring',
    emoji: '🌸',
    buttonRadius: '12px',
    bgPattern: 'dots',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#16a34a',
      '--tp-tertiary': '#eab308',
      '--tp-bg': '#f0fdf4',
      '--tp-surface': '#ffffff',
      '--tp-text': '#166534',
      '--tp-text-secondary': '#6b7280',
      '--tp-border': '#dcfce7',
      '--tp-header-bg': '#16a34a',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(22, 163, 74, 0.12)',
      '--tp-accent': '#facc15',
    },
  },
  ocean: {
    id: 'ocean',
    label: 'Ocean',
    emoji: '🌊',
    buttonRadius: '9999px',
    bgPattern: 'waves',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#2563eb',
      '--tp-tertiary': '#f59e0b',
      '--tp-bg': '#eff6ff',
      '--tp-surface': '#ffffff',
      '--tp-text': '#1e3a5f',
      '--tp-text-secondary': '#64748b',
      '--tp-border': '#dbeafe',
      '--tp-header-bg': '#2563eb',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(37, 99, 235, 0.12)',
      '--tp-accent': '#f59e0b',
    },
  },
  rose: {
    id: 'rose',
    label: 'Rose',
    emoji: '🌹',
    buttonRadius: '8px',
    bgPattern: 'none',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#e11d48',
      '--tp-tertiary': '#fbbf24',
      '--tp-bg': '#fff1f2',
      '--tp-surface': '#ffffff',
      '--tp-text': '#881337',
      '--tp-text-secondary': '#9f1239',
      '--tp-border': '#ffe4e6',
      '--tp-header-bg': '#e11d48',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(225, 29, 72, 0.12)',
      '--tp-accent': '#fbbf24',
    },
  },
  lavender: {
    id: 'lavender',
    label: 'Lavender',
    emoji: '💜',
    buttonRadius: '12px',
    bgPattern: 'grid',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#7c3aed',
      '--tp-tertiary': '#f59e0b',
      '--tp-bg': '#faf5ff',
      '--tp-surface': '#ffffff',
      '--tp-text': '#4c1d95',
      '--tp-text-secondary': '#7c3aed',
      '--tp-border': '#f3e8ff',
      '--tp-header-bg': '#7c3aed',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(124, 58, 237, 0.12)',
      '--tp-accent': '#f59e0b',
    },
  },
  sunset: {
    id: 'sunset',
    label: 'Sunset',
    emoji: '🌅',
    buttonRadius: '6px',
    bgPattern: 'none',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#ea580c',
      '--tp-tertiary': '#d946ef',
      '--tp-bg': '#fff7ed',
      '--tp-surface': '#ffffff',
      '--tp-text': '#7c2d12',
      '--tp-text-secondary': '#9a3412',
      '--tp-border': '#ffedd5',
      '--tp-header-bg': '#ea580c',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(234, 88, 12, 0.12)',
      '--tp-accent': '#d946ef',
    },
  },
  midnight: {
    id: 'midnight',
    label: 'Midnight',
    emoji: '🌙',
    buttonRadius: '4px',
    bgPattern: 'stars',
    css: {
      '--tp-primary': '#1e293b',
      '--tp-secondary': '#38bdf8',
      '--tp-tertiary': '#facc15',
      '--tp-bg': '#0f172a',
      '--tp-surface': '#1e293b',
      '--tp-text': '#f1f5f9',
      '--tp-text-secondary': '#94a3b8',
      '--tp-border': '#334155',
      '--tp-header-bg': '#0f172a',
      '--tp-header-text': '#38bdf8',
      '--tp-card-shadow': '0 4px 20px rgba(56, 189, 248, 0.1)',
      '--tp-accent': '#facc15',
    },
  },
  forest: {
    id: 'forest',
    label: 'Forest',
    emoji: '🌲',
    buttonRadius: '9999px',
    bgPattern: 'dots',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#059669',
      '--tp-tertiary': '#d97706',
      '--tp-bg': '#f0fdf4',
      '--tp-surface': '#ffffff',
      '--tp-text': '#14532d',
      '--tp-text-secondary': '#6b7280',
      '--tp-border': '#dcfce7',
      '--tp-header-bg': '#059669',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(5, 150, 105, 0.12)',
      '--tp-accent': '#d97706',
    },
  },
  cherry: {
    id: 'cherry',
    label: 'Cherry Blossom',
    emoji: '🎀',
    buttonRadius: '9999px',
    bgPattern: 'none',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#db2777',
      '--tp-tertiary': '#fde68a',
      '--tp-bg': '#fdf2f8',
      '--tp-surface': '#ffffff',
      '--tp-text': '#831843',
      '--tp-text-secondary': '#9d174d',
      '--tp-border': '#fce7f3',
      '--tp-header-bg': '#db2777',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(219, 39, 119, 0.12)',
      '--tp-accent': '#fde68a',
    },
  },
  candy: {
    id: 'candy',
    label: 'Candy',
    emoji: '❤️',
    buttonRadius: '9999px',
    bgPattern: 'dots',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#f43f5e',
      '--tp-tertiary': '#fbbf24',
      '--tp-bg': '#fff1f2',
      '--tp-surface': '#ffffff',
      '--tp-text': '#9f1239',
      '--tp-text-secondary': '#be185d',
      '--tp-border': '#ffe4e6',
      '--tp-header-bg': '#f43f5e',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(244, 63, 94, 0.12)',
      '--tp-accent': '#fbbf24',
    },
  },
  space: {
    id: 'space',
    label: 'Space',
    emoji: '🚀',
    buttonRadius: '4px',
    bgPattern: 'stars',
    css: {
      '--tp-primary': '#1e1b4b',
      '--tp-secondary': '#a78bfa',
      '--tp-tertiary': '#f59e0b',
      '--tp-bg': '#0f0d1a',
      '--tp-surface': '#1e1b4b',
      '--tp-text': '#f5f3ff',
      '--tp-text-secondary': '#8b83ba',
      '--tp-border': '#2e2a5e',
      '--tp-header-bg': '#0f0d1a',
      '--tp-header-text': '#a78bfa',
      '--tp-card-shadow': '0 4px 20px rgba(167, 139, 250, 0.1)',
      '--tp-accent': '#f59e0b',
    },
  },
  gold: {
    id: 'gold',
    label: 'Gold',
    emoji: '👑',
    buttonRadius: '9999px',
    bgPattern: 'none',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#d97706',
      '--tp-tertiary': '#fde68a',
      '--tp-bg': '#fffbeb',
      '--tp-surface': '#ffffff',
      '--tp-text': '#78350f',
      '--tp-text-secondary': '#92400e',
      '--tp-border': '#fde68a',
      '--tp-header-bg': '#d97706',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(217, 119, 6, 0.15)',
      '--tp-accent': '#fde68a',
    },
  },
  sky: {
    id: 'sky',
    label: 'Sky',
    emoji: '☁️',
    buttonRadius: '8px',
    bgPattern: 'waves',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#0ea5e9',
      '--tp-tertiary': '#a7f3d0',
      '--tp-bg': '#f0f9ff',
      '--tp-surface': '#ffffff',
      '--tp-text': '#0c4a6e',
      '--tp-text-secondary': '#64748b',
      '--tp-border': '#e0f2fe',
      '--tp-header-bg': '#0ea5e9',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(14, 165, 233, 0.12)',
      '--tp-accent': '#a7f3d0',
    },
  },
}

export const themeList = Object.values(themes)

export function applyThemeVars(root, themeId) {
  const theme = themes[themeId]
  if (!theme) return
  const vars = theme.css
  Object.entries(vars).forEach(([key, val]) => {
    root.style.setProperty(key, val)
  })
  root.style.setProperty('--tp-btn-radius', theme.buttonRadius || '12px')
  root.style.setProperty('--tp-bg-pattern', theme.bgPattern || 'none')
}
