export const themes = {
  spring: {
    id: 'spring',
    label: 'Spring',
    emoji: '🌸',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#16a34a',
      '--tp-tertiary': '#eab308',
      '--tp-bg': '#f0fdf4',
      '--tp-surface': '#ffffff',
      '--tp-text': '#166534',
      '--tp-text-secondary': '#6b7280',
      '--tp-border': '#dcfce7',
      '--tp-header-bg': '#16a34a',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(22, 163, 74, 0.12)',
      '--tp-accent': '#facc15',
    },
  },
  ocean: {
    id: 'ocean',
    label: 'Ocean',
    emoji: '🌊',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#2563eb',
      '--tp-tertiary': '#f59e0b',
      '--tp-bg': '#eff6ff',
      '--tp-surface': '#ffffff',
      '--tp-text': '#1e3a5f',
      '--tp-text-secondary': '#64748b',
      '--tp-border': '#dbeafe',
      '--tp-header-bg': '#2563eb',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(37, 99, 235, 0.12)',
      '--tp-accent': '#f59e0b',
    },
  },
  rose: {
    id: 'rose',
    label: 'Rose',
    emoji: '🌹',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#e11d48',
      '--tp-tertiary': '#fbbf24',
      '--tp-bg': '#fff1f2',
      '--tp-surface': '#ffffff',
      '--tp-text': '#881337',
      '--tp-text-secondary': '#9f1239',
      '--tp-border': '#ffe4e6',
      '--tp-header-bg': '#e11d48',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(225, 29, 72, 0.12)',
      '--tp-accent': '#fbbf24',
    },
  },
  lavender: {
    id: 'lavender',
    label: 'Lavender',
    emoji: '💜',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#7c3aed',
      '--tp-tertiary': '#f59e0b',
      '--tp-bg': '#faf5ff',
      '--tp-surface': '#ffffff',
      '--tp-text': '#4c1d95',
      '--tp-text-secondary': '#7c3aed',
      '--tp-border': '#f3e8ff',
      '--tp-header-bg': '#7c3aed',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(124, 58, 237, 0.12)',
      '--tp-accent': '#f59e0b',
    },
  },
  sunset: {
    id: 'sunset',
    label: 'Sunset',
    emoji: '🌅',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#ea580c',
      '--tp-tertiary': '#d946ef',
      '--tp-bg': '#fff7ed',
      '--tp-surface': '#ffffff',
      '--tp-text': '#7c2d12',
      '--tp-text-secondary': '#9a3412',
      '--tp-border': '#ffedd5',
      '--tp-header-bg': '#ea580c',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(234, 88, 12, 0.12)',
      '--tp-accent': '#d946ef',
    },
  },
  midnight: {
    id: 'midnight',
    label: 'Midnight',
    emoji: '🌙',
    css: {
      '--tp-primary': '#1e293b',
      '--tp-secondary': '#38bdf8',
      '--tp-tertiary': '#facc15',
      '--tp-bg': '#0f172a',
      '--tp-surface': '#1e293b',
      '--tp-text': '#f1f5f9',
      '--tp-text-secondary': '#94a3b8',
      '--tp-border': '#334155',
      '--tp-header-bg': '#0f172a',
      '--tp-header-text': '#38bdf8',
      '--tp-card-shadow': '0 4px 20px rgba(56, 189, 248, 0.1)',
      '--tp-accent': '#facc15',
    },
  },
  forest: {
    id: 'forest',
    label: 'Forest',
    emoji: '🌲',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#059669',
      '--tp-tertiary': '#d97706',
      '--tp-bg': '#f0fdf4',
      '--tp-surface': '#ffffff',
      '--tp-text': '#14532d',
      '--tp-text-secondary': '#6b7280',
      '--tp-border': '#dcfce7',
      '--tp-header-bg': '#059669',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(5, 150, 105, 0.12)',
      '--tp-accent': '#d97706',
    },
  },
  cherry: {
    id: 'cherry',
    label: 'Cherry Blossom',
    emoji: '🎀',
    css: {
      '--tp-primary': '#ffffff',
      '--tp-secondary': '#db2777',
      '--tp-tertiary': '#fde68a',
      '--tp-bg': '#fdf2f8',
      '--tp-surface': '#ffffff',
      '--tp-text': '#831843',
      '--tp-text-secondary': '#9d174d',
      '--tp-border': '#fce7f3',
      '--tp-header-bg': '#db2777',
      '--tp-header-text': '#ffffff',
      '--tp-card-shadow': '0 4px 20px rgba(219, 39, 119, 0.12)',
      '--tp-accent': '#fde68a',
    },
  },
}

export const themeList = Object.values(themes)

export function applyThemeVars(root, themeId) {
  const theme = themes[themeId]
  if (!theme) return
  const vars = theme.css
  Object.entries(vars).forEach(([key, val]) => {
    root.style.setProperty(key, val)
  })
}
